import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import React from 'react';
import Dashboard from '../app/ui';
import ReasonAnalysis from '../app/reason-analysis';
import {dashboard,runPlan} from '../lib/query';
const require=createRequire(import.meta.url),testRequire=createRequire(resolve('.sites-runtime/session-ui/package.json'));
require('react');require.cache[testRequire.resolve('react')]=require.cache[require.resolve('react')];
const {create,act}=testRequire('react-test-renderer');
(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true;
(globalThis as any).window={location:{hash:''},history:{replaceState(){}},scrollTo(){},addEventListener(){},removeEventListener(){}};
const requests:Array<{path:string,body:any}>=[];
globalThis.fetch=(async(url:any,options:any)=>{
 const u=new URL(url,'https://test.invalid'),body=options.body?JSON.parse(options.body):undefined;requests.push({path:u.pathname,body});
 if(u.pathname==='/api/meta')return Response.json({owner:true,months:[{month:'2017-02',cutoff:'2017-02-28'},{month:'2017-03',cutoff:'2017-03-31'}],channels:['Direct','Organic Search']});
 if(u.pathname==='/api/dashboard')return Response.json(await dashboard(JSON.parse(u.searchParams.get('filters')!),{overview:u.searchParams.get('view')==='overview'}));
 if(u.pathname==='/api/query')return Response.json(await runPlan(body));
 if(u.pathname==='/api/saved')return Response.json([]);
 throw Error('Unexpected request '+u.pathname);
}) as typeof fetch;
let view:any;
const settle=()=>new Promise(r=>setTimeout(r,0));
await act(async()=>{view=create(<Dashboard/>);await settle()});
assert.deepEqual(requests.map(r=>r.path).sort(),['/api/dashboard','/api/meta']);
const button=(t:string)=>view.root.findAllByType('button').find((b:any)=>b.children.join('')===t);
const click=async(t:string)=>{assert.ok(button(t),'Missing '+t);await act(async()=>{button(t).props.onClick();await settle()})};
// Choose March, then use the displayed server snapshot with no analysis request.
const month=view.root.findAllByType('input').find((n:any)=>n.props.type==='checkbox'&&n.parent.children.includes('2017-03'));
assert.ok(month);assert.equal(month.props.checked,true);assert.equal(button('数据管理'),undefined);assert.equal(button('AI 分析师'),undefined);
const before=requests.length;
await act(async()=>{view.root.findByProps({'aria-label':'查看GMV分析'}).props.onClick();await settle()});
assert.equal(requests.length,before);assert.equal(view.root.findByType(ReasonAnalysis).props.snapshot.decomposition.metrics.revenue.current,4960);
await click('返回经营概览');
await act(async()=>{view.root.findByProps({'aria-label':'时间粒度'}).props.onChange({target:{value:'month'}});await settle()});
assert.equal(requests.at(-1)?.body.dimension,'month');
await click('深度分析');assert.equal(requests.at(-1)?.body.dimension,'channel');
await click('设备与行为');assert.equal(requests.at(-1)?.body.dimension,'device');
assert.equal(requests.filter(r=>r.path==='/api/saved').length,0);
assert.equal(button('已保存分析'),undefined);assert.equal(button('让 AI 解读'),undefined);
assert.equal(requests.filter(r=>r.path==='/api/analysis').length,0);
await act(async()=>view.unmount());
console.log('Dashboard request flow: no hidden panels, zero-request KPI entry, lazy month/channel/device/saved passed.');
