import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import assert from 'node:assert/strict';
import {DimensionResults} from '../app/dimension-analysis';
import {decompose,dimensionResult} from '../lib/discovery/foundation';
import {recommend} from '../lib/discovery/recommendation';
const c={visitors:11000,buyers:100,transactions:120,revenue:12000},p={...c,visitors:10000};
const make=(dimension:string,changes:number[])=>dimensionResult('visitors',dimension,changes.flatMap((delta,i)=>[{dimension:'Test '+i,period:'previous',...p,visitors:2000},{dimension:'Test '+i,period:'current',...c,visitors:2000+delta}]),c,p);
const render=(dimensions:any[],scope:any[]=[])=>{const data={decomposition:decompose(c,p),dimensions,recommendation:recommend(dimensions,scope.map(s=>s.dimension)),availableDimensions:dimensions.map(d=>d.dimension)};return renderToStaticMarkup(<DimensionResults data={data} selected={data.recommendation.dimension} onSelect={()=>{}} onDrill={()=>{}} scope={scope} metric="visitors" metricPath={['GMV','交易数','访客数']} onBack={()=>{}}/>)};
const device=render([make('channel',[250,250,250,250]),make('device',[900,50,50])]);
assert.ok(device.includes('系统建议查看：设备'));assert.ok(device.includes('继续分析'));assert.ok(device.includes('指标驱动'));assert.ok(device.includes('维度定位'));
assert.ok(device.includes('去重访客 +900'));assert.ok(!device.includes('贡献率'));
assert.ok(device.includes('查看渠道'));assert.ok(device.includes('查看设备（系统推荐）'));
const tied=render([make('channel',[700,150,150]),make('device',[699,151,150])]);
assert.ok(tied.includes('查看渠道'));assert.ok(tied.includes('查看设备'));assert.ok(tied.includes('信号接近'));assert.ok(!tied.includes('按渠道定位'));
const scoped=render([make('channel',[900,50,50])],[{dimension:'device',value:'mobile'}]);
assert.ok(scoped.includes('设备：mobile'));assert.ok(scoped.includes('返回上一级'));assert.ok(scoped.includes('系统建议继续查看：渠道'));assert.ok(!scoped.includes('aria-label="继续分析'));
assert.ok(scoped.includes('查看渠道'));assert.ok(!scoped.includes('查看设备'));
console.log('Phase 2 rendering: recommendation, ties, scoped path, back control, distinct wording and terminal state passed.');
