import assert from 'node:assert/strict';import {GET,POST} from '../app/api/[...path]/route.ts';import {sql,env} from './storage.mjs';import {normalize} from '../lib/normalize.ts';import fs from 'node:fs';
const sample=JSON.parse(fs.readFileSync(new URL('../lib/sample.json',import.meta.url),'utf8'));let count=0;
async function call(path,body,owner=true,cookie='',method){const headers={'Content-Type':'application/json',Origin:'https://site.test',...(owner?{'oai-authenticated-user-id':'test-owner','oai-authenticated-user-email':'owner@example.invalid'}:{}),...(cookie?{Cookie:cookie}:{})};const r=await (body===undefined?GET:POST)(new Request('https://site.test/api/'+path,{method:method||(body===undefined?'GET':'POST'),headers,...(body===undefined?{}:{body:JSON.stringify(body)})}));let b;try{b=await r.json()}catch{b={}}return {status:r.status,b,headers:r.headers}}
function check(ok,msg){assert.ok(ok,msg);console.log('PASS',msg);count++}
check((await call('admin',undefined,false)).status!==200,'admin rejects anonymous');check((await call('sample')).status===405,'GET cannot mutate');
let r=await call('sample',{});check(r.status===200,'sample loads');r=await call('sample',{});check(r.status===200,'sample load idempotent');
r=await call('dashboard?filters='+encodeURIComponent(JSON.stringify({sample:true})));check(r.b.total.sessions===90&&r.b.total.transactions===30,'sample sessions and transaction totals');
check(sql.prepare('SELECT SUM(purchase_events) n FROM sessions').get().n===60,'60 purchase events preserved diagnostically');check(sql.prepare('SELECT SUM(transaction_ids) n FROM sessions').get().n===30,'duplicate transaction IDs collapse');
const p=sample.find(s=>s.hits.some(h=>h.eCommerceAction?.action_type==='6'));const norm=normalize(p);check(norm.session.transactions===1&&norm.session.purchase_events===2,'order count independent of event count');const ps=norm.products.filter(p=>p.purchases);check(ps.every(p=>p.quantity>=0),'deduplicated product quantities');
check((await call('dashboard?filters=%7B%22sample%22%3Atrue%7D',undefined,false)).status!==200,'sample inaccessible to visitors');
check((await call('query',{dimension:'product',metrics:['product_revenue'],filters:{sample:true},product:"' OR 1=1--"})).b.rows.length===0,'search injection remains literal');check((await call('query',{dimension:'total;DROP TABLE sessions',metrics:['revenue']})).status!==200,'unapproved SQL dimensions rejected');
// Stage two months for same visitor. Dashboard remains unchanged until activation.
async function stage(name,date,hash){const st=await call('import/start',{name,hash});assert.equal(st.status,200);const id=st.b.id;const s=structuredClone(sample[0]);s.date=date;s.fullVisitorId='shared-visitor';s.visitId=date;let r=await call('import/chunk?id='+id,{n:0,records:[s]});assert.equal(r.status,200);r=await call('import/chunk?id='+id,{n:0,records:[s]});assert.equal(r.b.duplicate,true);return id}
const a=await stage('feb.jsonl','20170201','a'.repeat(64)),b=await stage('mar.jsonl','20170301','b'.repeat(64));check((await call('dashboard')).b.total.sessions===0,'staged imports invisible');await call('import/preview?id='+a,{});r=await call('import/commit?id='+a,{});check(r.status!==200,'incomplete/raw-missing import cannot commit');
sql.prepare('INSERT INTO months VALUES(?,?)').run('2017-02',a);sql.prepare('INSERT INTO months VALUES(?,?)').run('2017-03',b);r=await call('dashboard');check(r.b.total.sessions===2&&r.b.total.visitors===1,'cross-month visitors deduplicate');
r=await call('saved',{name:'visitors',plan:{dimension:'month',metrics:['visitors']},follow:true});check(r.status===200,'save validated query');r=await call('saved?filters='+encodeURIComponent(JSON.stringify({months:['2017-02']})));check(r.b[0].result.rows.length===1,'saved query follows filters');
r=await call('query',{dimension:'channel_month',metrics:['revenue']});check(r.status===200&&r.b.rows.length===2,'monthly channel comparison supported');
r=await call('settings',{key:'test-key-1234567890',visitorEnabled:true,dailyLimit:10});check(r.status===200&&!sql.prepare("SELECT value FROM settings WHERE key='model_key'").get().value.includes('test-key'),'model credential encrypted');
let modelCalls=0;globalThis.fetch=async()=>{modelCalls++;return Response.json({choices:[{message:{content:modelCalls%2===1?JSON.stringify({dimension:'total',metrics:['visitors']}):'当前筛选范围内共有 1 位去重访客。'}}],usage:{total_tokens:10}})};
const cookie='analytics_visitor=11111111-1111-4111-8111-111111111111';for(let i=0;i<3;i++){r=await call('ask',{question:'访客数'},false,cookie);assert.equal(r.status,200,JSON.stringify(r.b))}check((await call('ask',{question:'访客数'},false,cookie)).status===429,'fourth successful visitor question blocked');
await call('settings',{visitorEnabled:false});check((await call('ask',{question:'访客数'},false,'analytics_visitor=22222222-2222-4222-8222-222222222222')).status!==200,'visitor switch blocks remaining quota');await call('settings',{visitorEnabled:true});globalThis.fetch=async()=>new Response('',{status:500});r=await call('ask',{question:'访客数'},false,'analytics_visitor=33333333-3333-4333-8333-333333333333');check(r.status!==200&&sql.prepare("SELECT count(*) n FROM calls WHERE visitor=? AND status='success'").get('33333333-3333-4333-8333-333333333333').n===0,'model failure does not consume success quota');
console.log(`${count} integration checks passed; model requests mocked, no live API key used.`);
