import assert from 'node:assert/strict';import {GET,POST} from '../app/api/[...path]/route.ts';import {sql} from './storage.mjs';import {fields} from '../lib/semantic/dictionary.ts';import {profile} from '../lib/semantic/profile.ts';import {parseTime} from '../lib/semantic/normalize.ts';import {readRecords} from '../lib/semantic/parse.ts';
let passed=0;function check(v,label){assert.ok(v,label);console.log('PASS',label);passed++}
async function api(path,body,owner=true){const req=new Request('https://site.test/api/semantic/'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',Origin:'https://site.test',...(owner?{'oai-authenticated-user-id':'test-owner','oai-authenticated-user-email':'owner@example.invalid'}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});const res=await (body===undefined?GET:POST)(req);const b=await res.json();return {status:res.status,b}}
const mapping={订单编号:'order_id',客户编号:'user_id',实付金额:'amount',下单时间:'event_time',购买件数:'quantity',SKU:'product_id',明细编号:'line_id',渠道:'channel'};
const base={grain:'order_items',mapping,amountScope:'order_total',amountMeaning:'paid',currency:'CNY',unit:1,timeRole:'order',timezone:'Asia/Shanghai',deduplicate:true,paidOnly:true,fullTraffic:false,eventMap:{},confirmed:true};
const rows=[{'订单编号':'0001','客户编号':'U1','实付金额':'100','下单时间':'2026-08-01 12:00:00','购买件数':'2','SKU':'P1','明细编号':'L1','渠道':'广告'},{'订单编号':'0001','客户编号':'U1','实付金额':'100','下单时间':'2026-08-01 12:00:00','购买件数':'1','SKU':'P2','明细编号':'L2','渠道':'广告'},{'订单编号':'0002','客户编号':'U1','实付金额':'50','下单时间':'2026-08-02 12:00:00','购买件数':'1','SKU':'P1','明细编号':'L1','渠道':'广告'}];let nextHash=1;
async function create(data,cfg=base){const headers=[...new Set(data.flatMap(Object.keys))];const p=await api('profile',{headers,records:data,name:'test.csv',hash:(nextHash++).toString(16).padStart(64,'0')});assert.equal(p.status,200,JSON.stringify(p.b));const id=p.b.dataset.id;const conf=await api('config?id='+id,cfg);assert.equal(conf.status,200,JSON.stringify(conf.b));sql.prepare('UPDATE datasets SET raw=1 WHERE id=?').run(id);const b={n:0,start:1,records:data};const ingest=await api('chunk?id='+id,b);assert.equal(ingest.status,200,JSON.stringify(ingest.b));const repeat=await api('chunk?id='+id,b);assert.equal(repeat.b.duplicate,true);const f=await api('finish?id='+id,{expectedRows:data.length});assert.equal(f.status,200,JSON.stringify(f.b));return {id,report:f.b}}
const sampleProfile=profile(['订单数量','创建日期','客户编号'],[{'订单数量':'2','创建日期':'2026-08-01','客户编号':'000001'}]);check(sampleProfile[0].candidates[0].score<75&&sampleProfile[1].candidates[0].score<75,'ambiguous names get low heuristic scores');check(sampleProfile[2].suggested==='user_id','alias and content jointly identify user ID');
check((await api('list',undefined,false)).status===400,'semantic data requires owner');check((await api('activate?id=x')).status===405,'GET cannot activate data');
let x=await create([...rows,rows[0]]);const metric=k=>x.report.metrics.find(m=>m.key===k);check(x.report.duplicates===1&&x.report.effectiveRows===3,'full-row duplicates removed only after explicit configuration');check(metric('orders').value===2&&metric('amount').value===150&&metric('aov').value===75,'repeated order total across items counts only once');check(metric('buyers').value===1,'buyers deduplicate across orders');check(metric('quantity').value===4,'quantity sums unique order lines');check(metric('conversion').value===null&&metric('visitors').value===null,'order-only data never manufactures visitors or conversion');check(sql.prepare('SELECT order_id FROM standard_rows WHERE dataset_id=? LIMIT 1').get(x.id).order_id==='0001','leading zero IDs survive');check((await api('activate?id='+x.id,{})).status===200,'clean dataset activates');check((await api('config?id='+x.id,base)).status!==200,'active mapping cannot be silently overwritten');
const lines=structuredClone(rows);lines[0]['实付金额']='60';lines[1]['实付金额']='40';x=await create(lines,{...base,amountScope:'line_total'});check(x.report.metrics.find(m=>m.key==='amount').value===150,'line-level amount is summed at confirmed grain');
const bad=structuredClone(rows);bad[1]['实付金额']='999';x=await create(bad);check(x.report.errors>0&&x.report.metrics.every(m=>m.value===null),'conflicting order totals block all official metrics');check((await api('activate?id='+x.id,{})).status!==200,'quality blocker prevents activation');
const missing=structuredClone(rows);missing[2]['实付金额']='';x=await create(missing);check(x.report.errors===0&&x.report.metrics.find(m=>m.key==='orders').value===2&&x.report.metrics.find(m=>m.key==='amount').value===null,'missing amount disables only dependent metrics, not filled with zero');
x=await create([...rows,rows[0]],{...base,deduplicate:false});check(x.report.errors>0,'unconfirmed duplicate removal blocks activation');
const invalid=structuredClone(rows);invalid[0]['下单时间']='2026-02-30';invalid[1]['购买件数']='-2';x=await create(invalid);check(x.report.errors>=2,'impossible dates and negative quantities detected in full scan');
const emap={用户:'user_id',时间:'event_time',行为:'event_type',订单:'order_id',金额:'amount',事件:'event_id',商品:'product_id',会话:'session_id'};const ec={...base,grain:'events',mapping:emap,timeRole:'event',fullTraffic:true,eventMap:{浏览:'view',购买:'purchase'},amountScope:'order_total'};
const events=[{用户:'u1',时间:'2026-08-01 10:00:00',行为:'浏览',订单:'',金额:'',事件:'e1',商品:'p1',会话:'s1'},{用户:'u2',时间:'2026-08-01 10:00:00',行为:'浏览',订单:'',金额:'',事件:'e2',商品:'p1',会话:'s2'},{用户:'u1',时间:'2026-08-01 10:10:00',行为:'购买',订单:'o1',金额:'100',事件:'e3',商品:'p1',会话:'s1'},{用户:'u1',时间:'2026-08-01 10:10:01',行为:'购买',订单:'o1',金额:'100',事件:'e4',商品:'p1',会话:'s1'}];x=await create(events,ec);check(x.report.metrics.find(m=>m.key==='orders').value===1&&x.report.metrics.find(m=>m.key==='conversion').value===.5,'duplicate purchase events do not double order count or conversion');
x=await create(events,{...ec,fullTraffic:false});check(x.report.metrics.find(m=>m.key==='visitors').value===null,'unconfirmed traffic coverage suppresses denominator');
const noID=structuredClone(events);noID[2]['订单']='';x=await create(noID,ec);check(x.report.metrics.find(m=>m.key==='orders').value===null,'purchase without transaction ID cannot become an order');
const unseen=structuredClone(events);unseen[0]['行为']='未确认新事件';x=await create(unseen,ec);check(x.report.errors>0,'event values missing from mapping block full import');
check(parseTime('2026-08-01T23:30:00Z','Asia/Shanghai').date==='2026-08-02','time zone changes calendar date explicitly');let failed=false;try{parseTime('2026-11-01 01:30:00','America/Los_Angeles')}catch{failed=true}check(failed,'ambiguous DST local time requires explicit offset');
const csv='订单编号,商品名称,实付金额\r\n0001,"红色,\"\"特别版\"\"\nT恤",100\r\n';const parsed=[];for await(const r of readRecords(new File([csv],'orders.csv')))parsed.push(r);check(parsed.length===1&&parsed[0]['订单编号']==='0001'&&parsed[0]['商品名称']==='红色,"特别版"\nT恤','streaming CSV handles quoted commas, escaped quotes, and newlines');
check((await api('dictionary')).b.fields.length===fields.length,'dictionary available from server');console.log(`${passed} semantic checks passed.`);
