import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import React from 'react';
import ReasonAnalysis from '../app/reason-analysis';
import DimensionAnalysis from '../app/dimension-analysis';
import StepConclusion from '../app/step-conclusion';
import {analyze} from '../lib/discovery/analysis';
import {execute,queryLog} from './analysis-db';
const require=createRequire(import.meta.url),testRequire=createRequire(resolve('.sites-runtime/session-ui/package.json'));
require('react');require.cache[testRequire.resolve('react')]=require.cache[require.resolve('react')];
const {create,act}=testRequire('react-test-renderer');
(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true;
// Synthetic interaction fixture, not the production GA dataset.
execute(`WITH RECURSIVE n(x) AS (SELECT 1 UNION ALL SELECT x+1 FROM n WHERE x<1200) INSERT INTO sessions SELECT 'mar','ui-'||x,'2017-03-01','2017-03','new-'||x,CASE WHEN x<1050 THEN 'Organic Search' ELSE 'Direct' END,CASE WHEN x%2=0 THEN 'mobile' ELSE 'desktop' END,1,80,1,1,1,1,1,1 FROM n;
WITH RECURSIVE n(x) AS (SELECT 1 UNION ALL SELECT x+1 FROM n WHERE x<500) INSERT INTO sessions SELECT 'feb','ui-'||x,'2017-02-01','2017-02','old-'||x,CASE WHEN x<400 THEN 'Organic Search' ELSE 'Direct' END,CASE WHEN x%2=0 THEN 'mobile' ELSE 'desktop' END,1,100,1,1,1,1,1,1 FROM n;`);
let requests=0;
globalThis.fetch=(async(url:any)=>{requests++;const u=new URL(url,'https://test.invalid');return Response.json(await analyze(JSON.parse(u.searchParams.get('input')!)))}) as typeof fetch;
const snapshot:any=await analyze({filters:{months:['2017-03']}});let view:any;
await act(async()=>{view=create(<ReasonAnalysis snapshot={snapshot} card={{metric:'revenue'}}/>)});
const button=(text:string)=>view.root.findAllByType('button').find((b:any)=>b.children.join('')===text)||view.root.findAllByType('button').find((b:any)=>b.children.join('').startsWith(text));
const click=async(text:string)=>{assert.ok(button(text),'Missing button '+text);await act(async()=>{button(text).props.onClick();await new Promise(r=>setTimeout(r,0))})};
const conclusions=()=>view.root.findAllByType(StepConclusion).map((n:any)=>n.props.text);
const dimensionConclusions=()=>view.root.findByType(DimensionAnalysis).findAllByType(StepConclusion).map((n:any)=>n.props.text);
assert.equal(button('查看本次分析小结'),undefined);
assert.deepEqual(conclusions(),[snapshot.decomposition.summaries.revenue]);
await click(snapshot.decomposition.metrics.transactions.title);
assert.ok(conclusions().includes(snapshot.decomposition.summaries.transactions));
await click(snapshot.decomposition.metrics.visitors.title);
assert.equal(dimensionConclusions().length,1);
assert.ok(view.root.findAllByProps({className:'step-actions'}).length===0);
assert.ok(button(snapshot.decomposition.metrics.transactions.title).parent.props.className==='rate-node');
const beforeChoose=requests,sqlBefore=queryLog.length;
await click('查看渠道');
assert.equal(requests,beforeChoose);assert.equal(queryLog.length,sqlBefore);
assert.match(dimensionConclusions()[0],/全局筛选范围.*从渠道维度看/);
assert.ok(!dimensionConclusions()[0].includes('贡献率'));
const scopeButton=view.root.findAllByType('button').find((b:any)=>b.props['aria-label']?.startsWith('继续分析 '));assert.ok(scopeButton);
assert.equal(scopeButton.parent.type,'div');
assert.ok(scopeButton.parent.findAllByType('strong').length>0);
const group=scopeButton.props['aria-label'].replace('继续分析 ','');
await act(async()=>{scopeButton.props.onClick();await new Promise(r=>setTimeout(r,0))});
assert.ok(dimensionConclusions()[0].startsWith('在 '+group+' 渠道范围内'));
assert.match(dimensionConclusions()[0],/从设备维度看/);
await click('返回上一级');
assert.match(dimensionConclusions()[0],/全局筛选范围.*从渠道维度看/);
await click('查看设备');
assert.match(dimensionConclusions()[0],/全局筛选范围.*从设备维度看/);
assert.ok(!dimensionConclusions()[0].includes(group+' 渠道范围内'));
const deviceButton=view.root.findAllByType('button').find((b:any)=>b.props['aria-label']?.startsWith('继续分析 '));
const device=deviceButton.props['aria-label'].replace('继续分析 ','');
await act(async()=>{deviceButton.props.onClick();await new Promise(r=>setTimeout(r,0))});
assert.ok(dimensionConclusions()[0].startsWith('在 '+device+' 设备范围内'));
assert.match(dimensionConclusions()[0],/从渠道维度看/);
await act(async()=>{view.update(<ReasonAnalysis key="new-session" snapshot={snapshot} card={{metric:'revenue'}}/>)});
assert.equal(view.root.findAllByType(DimensionAnalysis).length,0);
assert.deepEqual(conclusions(),[snapshot.decomposition.summaries.revenue]);
await act(async()=>view.unmount());
// No unique recommendation still renders a default view; a device recommendation wins over list order.
for(const recommended of [null,'device']){
 const data:any=await analyze({metric:'visitors',filters:{months:['2017-03']},recommendation:'auto'});
 data.recommendation={...data.recommendation,dimension:recommended};
 const {responseKey}=await import('../lib/analysis-session');
 await act(async()=>{view=create(<DimensionAnalysis snapshot={snapshot} metric="visitors" metricPath={['访客数']} responses={{[responseKey('visitors',[])]:data}}/>)});
 assert.equal(conclusions().length,1);
 assert.ok(conclusions()[0].includes(recommended==='device'?'从设备维度看':'从渠道维度看'));
 await click(recommended==='device'?'查看渠道':'查看设备');
 assert.ok(conclusions()[0].includes(recommended==='device'?'从渠道维度看':'从设备维度看'));
 await act(async()=>view.unmount());
} 
console.log('Step UI passed: metric conclusions, automatic dimension view and card-contained actions, both drill orders, scope, back, switching, reset, no summary and no selection SQL.');

