import {fields,Config} from './dictionary';
export type Issue={severity:'error'|'warning';field:string;code:string;message:string};
const empty=(v:any)=>v==null||String(v).trim()==='';
function localParts(ms:number,tz:string){return Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(ms).filter(p=>p.type!=='literal').map(p=>[p.type,p.value]))}
export function parseTime(v:any,tz:string){const str=String(v).trim();if(/(?:Z|[+-]\d{2}:?\d{2})$/i.test(str)){if(!/^\d{4}-\d{2}-\d{2}T/.test(str))throw Error('请使用 ISO 时间格式');const ms=Date.parse(str);if(!Number.isFinite(ms))throw Error('时间无效');const inputDate=str.slice(0,10);if(!validDate(inputDate))throw Error('日期不存在');const p=localParts(ms,tz);return {time:new Date(ms).toISOString(),date:`${p.year}-${p.month}-${p.day}`}}
 const m=str.match(/^(\d{4})[-/]?(\d{2})[-/]?(\d{2})(?:[ T](\d{2}):(\d{2})(?::(\d{2})(?:\.(\d{1,3}))?)?)?$/);if(!m)throw Error('需 YYYY-MM-DD、YYYYMMDD 或 ISO 日期时间；不猜测日/月顺序和时间戳单位');const [y,mo,d,h,mi,se]=[m[1],m[2],m[3],m[4]||'00',m[5]||'00',m[6]||'00'].map(Number);const wall=Date.UTC(y,mo-1,d,h,mi,se);if(!validDate(`${m[1]}-${m[2]}-${m[3]}`)||h>23||mi>59||se>59)throw Error('日期或时间不存在');let utc=wall;for(let i=0;i<4;i++){const p=localParts(utc,tz);const got=Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute,+p.second);utc+=wall-got}const target=[m[1],m[2],m[3],m[4]||'00',m[5]||'00',m[6]||'00'].join('');const toWall=(t:number)=>{const p=localParts(t,tz);return p.year+p.month+p.day+p.hour+p.minute+p.second};if(toWall(utc)!==target)throw Error('该本地时间因夏令时不存在');if(toWall(utc-3600000)===target||toWall(utc+3600000)===target)throw Error('该本地时间有夏令时歧义，请在原文件写明时区偏移');return {time:new Date(utc+Number((m[7]||'').padEnd(3,'0'))).toISOString(),date:`${m[1]}-${m[2]}-${m[3]}`}}
function validDate(s:string){const [y,m,d]=s.split('-').map(Number);return y>=1900&&y<=2200&&new Date(Date.UTC(y,m-1,d)).toISOString().slice(0,10)===s}
export function normalizeStandard(raw:Record<string,any>,c:Config){if(!raw||Array.isArray(raw)||typeof raw!=='object'||Object.values(raw).some(v=>v!=null&&typeof v==='object'))throw Error('每行必须是扁平对象');const issues:Issue[]=[];const r:any=Object.fromEntries(fields.map(f=>[f.key,null]));r.event_date=null;
 for(const [column,key]of Object.entries(c.mapping)){if(!key)continue;const f=fields.find(f=>f.key===key)!;const v=raw[column];if(empty(v)){if(key==='event_time'||(c.grain!=='events'&&key==='order_id')||(c.grain==='events'&&key==='event_type')||(c.grain==='order_items'&&['product_id','line_id'].includes(key)))issues.push({severity:'error',field:key,code:'required_missing',message:'必需字段缺失'});continue}try{if(f.type==='number'){const s=String(v).trim();if(!/^[+]?(?:\d+\.?\d*|\.\d+)$/.test(s))throw Error('需非负纯数值，不自动猜测货币符号、千分位或退款含义');const n=Number(s);if(!Number.isFinite(n)||n>Number.MAX_SAFE_INTEGER)throw Error('数值超出安全范围');if(key==='quantity'&&!Number.isInteger(n))throw Error('商品件数必须为整数');r[key]=key==='amount'?n/Number(c.unit):n}else if(f.type==='time'){const t=parseTime(v,c.timezone);r.event_time=t.time;r.event_date=t.date}else{if(f.type==='id'&&typeof v!=='string'&&typeof v!=='number')throw Error('编号必须是文本或安全整数');if(f.type==='id'&&typeof v==='number'&&!Number.isSafeInteger(v))throw Error('编号已经超出安全整数精度，请在源文件中改为文本');r[key]=String(v).trim();if(r[key].length>500)throw Error('字段超过 500 字符');if(key==='event_type'){const mapped=c.eventMap[r[key]];if(!mapped)throw Error('发现尚未确认的行为取值 '+r[key].slice(0,60));r[key]=mapped}}}catch(e:any){issues.push({severity:'error',field:key,code:'invalid_value',message:e.message});r[key]=null}}
 if(c.grain!=='events')r.event_type='purchase';if(c.grain==='events'&&['add_to_cart','purchase','checkout','view'].includes(r.event_type)&&!r.product_id)issues.push({severity:'warning',field:'product_id',code:'unlinked_product',message:'该行为无法关联商品，商品分析或商品漏斗不可用'});
 if(r.event_type==='purchase'&&!r.order_id)issues.push({severity:'warning',field:'order_id',code:'purchase_without_order',message:'购买事件缺少交易编号，不能可靠计算订单数'});
 return {row:r,issues};}
export async function fingerprint(value:any){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(value)));return Array.from(new Uint8Array(digest)).map(n=>n.toString(16).padStart(2,'0')).join('')}
