import {db,rows,one,bucket} from '../db';import {fields,metricDictionary,Config,validateConfig} from './dictionary';import {profile} from './profile';import {normalizeStandard,fingerprint} from './normalize';
export async function getDataset(id:string){const d=await one('SELECT * FROM datasets WHERE id=?',[id]);if(!d)throw Error('找不到数据集');return {...d,headers:JSON.parse(d.headers),profile:JSON.parse(d.profile),config:d.config?JSON.parse(d.config):null,report:d.report?JSON.parse(d.report):null}}
export async function semanticProfile(b:any){if(!/^[a-f0-9]{64}$/.test(b.hash))throw Error('文件校验无效');const p=profile(b.headers,b.records);const old=await one("SELECT id FROM datasets WHERE hash=? AND status!='cancelled' ORDER BY created DESC LIMIT 1",[b.hash]);if(old)return {existing:true,dataset:await getDataset(old.id)};const id=crypto.randomUUID();await db().prepare('INSERT INTO datasets(id,name,hash,status,created,headers,profile) VALUES(?,?,?,?,?,?,?)').bind(id,String(b.name||'未命名数据集').slice(0,180),b.hash,'draft',new Date().toISOString(),JSON.stringify(b.headers),JSON.stringify(p)).run();return {dataset:await getDataset(id)}}
export async function setConfig(id:string,c:Config){const d=await getDataset(id);if(d.status==='active')throw Error('已启用的数据集不可直接改映射，请创建新版本');validateConfig(c,d.headers);const config:Config={grain:c.grain,mapping:c.mapping,amountScope:c.amountScope,amountMeaning:c.amountMeaning,currency:c.currency,unit:Number(c.unit),timeRole:c.timeRole,timezone:c.timezone,deduplicate:!!c.deduplicate,paidOnly:!!c.paidOnly,fullTraffic:c.grain==='events'&&!!c.fullTraffic,eventMap:c.eventMap||{},confirmed:true};await db().batch([db().prepare('DELETE FROM standard_rows WHERE dataset_id=?').bind(id),db().prepare('DELETE FROM semantic_chunks WHERE dataset_id=?').bind(id),db().prepare("UPDATE datasets SET config=?,status='mapped',report=NULL,revision=revision+1 WHERE id=?").bind(JSON.stringify(config),id)]);return {ok:true}}
export async function semanticIngest(id:string,b:any){const d=await getDataset(id);if(d.status!=='mapped')throw Error('请先确认映射，已完成检查的数据不可继续写入');if(!Number.isInteger(b.n)||b.n<0||!Number.isInteger(b.start)||b.start<1||!Array.isArray(b.records)||!b.records.length||b.records.length>200)throw Error('分批参数无效');const digest=await fingerprint(b.records);const prev=await one('SELECT digest FROM semantic_chunks WHERE dataset_id=? AND n=?',[id,b.n]);if(prev){if(prev.digest!==digest)throw Error('同一批次内容不一致，请重新检查');return {duplicate:true}}const c=d.config as Config;const data=[];for(let i=0;i<b.records.length;i++){const raw=b.records[i];if(Object.keys(raw).some(k=>!d.headers.includes(k)))throw Error('文件中途出现未声明字段');const normalized=normalizeStandard(raw,c);const ordered=Object.fromEntries(d.headers.map((h:string)=>[h,raw[h]??null]));data.push({dataset_id:id,row_no:b.start+i,row_hash:await fingerprint(ordered),...normalized.row,issues:JSON.stringify(normalized.issues)})}const columns=Object.keys(data[0]);const size=Math.floor(95/columns.length);const stmts=[];for(let i=0;i<data.length;i+=size){const slice=data.slice(i,i+size);stmts.push(db().prepare(`INSERT INTO standard_rows(${columns.join(',')}) VALUES ${slice.map(()=>`(${columns.map(()=>'?').join(',')})`).join(',')}`).bind(...slice.flatMap(r=>columns.map(k=>(r as any)[k]))))}stmts.push(db().prepare('INSERT INTO semantic_chunks(dataset_id,n,digest,count) VALUES(?,?,?,?)').bind(id,b.n,digest,data.length));await db().batch(stmts);return {count:data.length}}
function cte(c:Config){return `WITH clean AS (SELECT * FROM standard_rows WHERE dataset_id=? ${c.deduplicate?'AND row_no IN (SELECT MIN(row_no) FROM standard_rows WHERE dataset_id=? GROUP BY row_hash)':''}), purchases AS (SELECT * FROM clean WHERE event_type='purchase') `}
function args(id:string,c:Config){return c.deduplicate?[id,id]:[id]}
export async function evaluate(id:string){const d=await getDataset(id),c=d.config as Config;if(!c)throw Error('尚未确认映射');const pre=cte(c),bind=args(id,c);const total=await one('SELECT COUNT(*) n,MIN(row_no) first_row,MAX(row_no) last_row,MIN(event_date) first_date,MAX(event_date) last_date FROM standard_rows WHERE dataset_id=?',[id]);
 const issues=await rows("SELECT json_extract(j.value,'$.severity') severity,json_extract(j.value,'$.field') field,json_extract(j.value,'$.code') code,json_extract(j.value,'$.message') message,COUNT(*) count,MIN(r.row_no) example_row FROM standard_rows r,json_each(r.issues) j WHERE r.dataset_id=? GROUP BY severity,field,code,message ORDER BY severity,count DESC LIMIT 100",[id]);
 const fieldStats=await one('SELECT '+fields.map(f=>`SUM(CASE WHEN ${f.key} IS NULL THEN 1 ELSE 0 END) AS ${f.key}`).join(',')+' FROM standard_rows WHERE dataset_id=?',[id]);const duplicate=await one('SELECT COALESCE(SUM(n-1),0) n FROM (SELECT COUNT(*) n FROM standard_rows WHERE dataset_id=? GROUP BY row_hash HAVING COUNT(*)>1)',[id]);const count=async(q:string)=>Number((await one(pre+q,bind))?.n||0);
 const add=(severity:string,code:string,message:string,n:number,field='')=>{if(n)issues.push({severity,code,message,count:n,field})};
 add(c.deduplicate?'warning':'error','exact_duplicates',c.deduplicate?'完全重复行已按确认规则去重，原文件仍保留':'发现完全重复行，请确认去重规则后重新检查',duplicate.n);
 const orderDup=await count("SELECT COUNT(*) n FROM (SELECT order_id FROM purchases WHERE order_id IS NOT NULL GROUP BY order_id HAVING COUNT(*)>1)");add('warning','repeated_order',c.grain==='orders'?'同一订单编号重复出现，将按编号去重，不重复累计金额':'同一订单关联多条明细或购买事件，指标按订单编号去重',orderDup,'order_id');
 const conflicts=await count(`SELECT COUNT(*) n FROM (SELECT order_id FROM purchases WHERE order_id IS NOT NULL GROUP BY order_id HAVING COUNT(DISTINCT user_id)>1 OR COUNT(DISTINCT channel)>1 OR COUNT(DISTINCT device)>1 ${c.grain!=='events'?'OR COUNT(DISTINCT event_date)>1':''} ${c.amountScope==='order_total'?'OR COUNT(DISTINCT amount)>1':''})`);add('error','order_conflict','同一订单的用户、渠道、设备、归属日或整单金额存在冲突，不能自动选择一条',conflicts,'order_id');
 const lines=await count("SELECT COUNT(*) n FROM (SELECT order_id,line_id FROM purchases WHERE order_id IS NOT NULL AND line_id IS NOT NULL GROUP BY order_id,line_id HAVING COUNT(DISTINCT product_id)>1 OR COUNT(DISTINCT amount)>1 OR COUNT(DISTINCT quantity)>1)");add('error','line_conflict','同一订单明细编号的商品、金额或件数冲突',lines,'line_id');
 const eventDup=await count('SELECT COUNT(*) n FROM (SELECT event_id FROM clean WHERE event_id IS NOT NULL GROUP BY event_id HAVING COUNT(*)>1)');const eventConflict=await count('SELECT COUNT(*) n FROM (SELECT event_id FROM clean WHERE event_id IS NOT NULL GROUP BY event_id HAVING COUNT(DISTINCT row_hash)>1)');add('error','event_conflict','同一事件编号对应不同记录，需在原始数据中核对',eventConflict,'event_id');add('warning','event_duplicates','重复事件编号已检查，订单指标仍按订单编号去重',eventDup,'event_id');
 if(c.grain==='events'&&!Object.values(c.mapping).includes('event_id'))add('warning','no_event_id','未提供事件编号，只能识别完全重复行，无法证明没有重复上报；严格事件漏斗暂不开放',1,'event_id');
 const negativePriceNote='金额不自动填零、不猜测币种，不同金额口径不可混算';
 const cellErrors=Number((await one("SELECT COUNT(*) n FROM standard_rows r,json_each(r.issues) j WHERE r.dataset_id=? AND json_extract(j.value,'$.severity')='error'",[id])).n);const errors=cellErrors+(c.deduplicate?0:Number(duplicate.n))+conflicts+lines+eventConflict;const overall=await one(pre+`SELECT COUNT(*) records,COUNT(DISTINCT user_id) visitors,SUM(CASE WHEN user_id IS NULL THEN 1 ELSE 0 END) missing_users,MIN(event_date) first_date,MAX(event_date) last_date FROM clean`,bind);
 const purchaseStats=await one(pre+`SELECT COUNT(*) records,COUNT(DISTINCT order_id) orders,COUNT(DISTINCT user_id) buyers,SUM(CASE WHEN order_id IS NULL THEN 1 ELSE 0 END) missing_orders,SUM(CASE WHEN user_id IS NULL THEN 1 ELSE 0 END) missing_users FROM purchases`,bind);
 const mapped=new Set(Object.values(c.mapping));const coverage=await one(pre+`SELECT COUNT(*) n FROM (SELECT order_id FROM purchases WHERE order_id IS NOT NULL GROUP BY order_id HAVING COUNT(amount)=0)`,bind);
 const amountSQL=pre+(c.amountScope==='order_total'?"SELECT SUM(amount) value FROM (SELECT order_id,MAX(amount) amount FROM purchases WHERE order_id IS NOT NULL GROUP BY order_id)":"SELECT SUM(amount) value FROM (SELECT order_id,line_id,MAX(amount) amount FROM purchases WHERE order_id IS NOT NULL AND line_id IS NOT NULL GROUP BY order_id,line_id)");
 const lineMissing=await count("SELECT COUNT(*) n FROM purchases WHERE line_id IS NULL OR amount IS NULL");const quantityMissing=await count("SELECT COUNT(*) n FROM purchases WHERE line_id IS NULL OR product_id IS NULL OR quantity IS NULL");
 const orderReason=!mapped.has('order_id')?'缺少 order_id，不能把购买事件数当成订单数':purchaseStats.missing_orders?'有购买记录缺少 order_id，订单数不完整':'';
 const amountReason=orderReason||(!mapped.has('amount')?'缺少 amount':(c.amountScope==='order_total'?coverage.n>0:lineMissing>0)?'部分购买订单或明细缺少金额，不能用零冒充真实收入':'');const buyerReason=orderReason||(!mapped.has('user_id')?'缺少 user_id':purchaseStats.missing_users?'部分购买记录缺少 user_id':'');const visitReason=c.grain!=='events'?'订单数据不包含未购买访客，需要完整访问行为数据':!c.fullTraffic?'尚未确认文件覆盖全部访客，不能用购买样本作分母':!mapped.has('user_id')?'缺少 user_id':overall.missing_users?'部分行为缺少 user_id':'';
 const amount=amountReason?null:(await one(amountSQL,bind))?.value??0;const metric=(key:string,value:any,reason:string,sql:string)=>({ ...metricDictionary.find(m=>m.key===key),value:errors||reason?null:value,status:errors?'blocked':reason?'unavailable':value==null?'unavailable':'available',reason:errors?'存在阻断性质量问题，请修复后再使用':reason|| (value==null?'分母为 0，暂不可计算':''),sql,params:bind,timeRole:c.timeRole,timezone:c.timezone,currency:c.currency,scope:{dataset:id,revision:d.revision,firstDate:overall.first_date,lastDate:overall.last_date}});
 const metrics=[metric('orders',purchaseStats.orders,orderReason,pre+"SELECT COUNT(DISTINCT order_id) value FROM purchases"),metric('amount',amount,amountReason,amountSQL),metric('buyers',purchaseStats.buyers,buyerReason,pre+'SELECT COUNT(DISTINCT user_id) value FROM purchases'),metric('aov',purchaseStats.orders?Number(amount)/purchaseStats.orders:null,amountReason,pre+'SELECT 1.0*('+amountSQL.slice(pre.length)+')/NULLIF((SELECT COUNT(DISTINCT order_id) FROM purchases),0) value'),metric('visitors',overall.visitors,visitReason,pre+'SELECT COUNT(DISTINCT user_id) value FROM clean'),metric('conversion',overall.visitors?purchaseStats.buyers/overall.visitors:null,buyerReason||visitReason,pre+"SELECT 1.0*COUNT(DISTINCT CASE WHEN event_type='purchase' THEN user_id END)/NULLIF(COUNT(DISTINCT user_id),0) value FROM clean"),metric('quantity',null,'', '')];
 const qReason=orderReason||(['orders'].includes(c.grain)?'订单总表不能推断商品明细销量':!mapped.has('quantity')||!mapped.has('line_id')||!mapped.has('product_id')?'缺少 quantity、line_id 或 product_id':quantityMissing?'部分购买明细缺少件数、商品编号或明细编号':'');const qsql=pre+'SELECT SUM(quantity) value FROM (SELECT order_id,line_id,MAX(quantity) quantity FROM purchases WHERE order_id IS NOT NULL AND line_id IS NOT NULL GROUP BY order_id,line_id)';metrics[6]=metric('quantity',qReason?null:((await one(qsql,bind))?.value??0),qReason,qsql);
 metrics[1].label=c.amountMeaning==='gmv'?'GMV':c.amountMeaning==='paid'?'实付金额':'GMV';
 const unlinked=await count("SELECT COUNT(*) n FROM clean WHERE event_type IN ('view','add_to_cart','checkout','purchase') AND product_id IS NULL");
 return {totalRows:total.n,effectiveRows:overall.records,duplicates:duplicate.n,errors,issues,fieldStats,firstDate:overall.first_date,lastDate:overall.last_date,metrics,capabilities:{product:!mapped.has('product_id')?'缺少 product_id':unlinked?'部分购物行为缺少 product_id，商品关联不完整':'具备商品关联字段',funnel:!mapped.has('session_id')?'缺少 session_id，暂不支持会话内严格漏斗':!mapped.has('event_id')?'缺少 event_id，重复事件无法充分核验':'字段已就绪；严格有序漏斗将在后续分析模块实现'},notes:[negativePriceNote,'完全重复行以原始字段内容生成指纹；行为事件中的重复购买不作为额外订单','本阶段只计算基础指标，不自动判定异常或生成因果结论','没有记录的日期不自动补零，也不把完整月份要求套用于新数据源'],config:c,revision:d.revision};}
export async function finishSemantic(id:string,b:any){const d=await getDataset(id);if(d.status!=='mapped')throw Error('数据集不在检查阶段');if(!d.raw)throw Error('请先保留原始文件');const totals=await one('SELECT COUNT(*) n,MIN(row_no) lo,MAX(row_no) hi FROM standard_rows WHERE dataset_id=?',[id]);if(!Number.isInteger(b.expectedRows)||b.expectedRows<1||totals.n!==b.expectedRows||totals.lo!==1||totals.hi!==b.expectedRows)throw Error('上传尚未完整，请重新处理文件');const report=await evaluate(id);await db().prepare('UPDATE datasets SET report=?,status=? WHERE id=?').bind(JSON.stringify(report),report.errors?'blocked':'review',id).run();return report}
export async function semanticRoute(path:string,req:Request,body:any){const url=new URL(req.url);const id=url.searchParams.get('id')||'';if(path==='semantic/dictionary')return {fields,metrics:metricDictionary};if(path==='semantic/list')return rows('SELECT id,name,status,created,revision FROM datasets ORDER BY created DESC LIMIT 100');if(path==='semantic/get')return getDataset(id);if(path==='semantic/profile')return semanticProfile(body);if(path==='semantic/config')return setConfig(id,body);
 if(path==='semantic/raw'){const d=await getDataset(id);if(req.method==='GET'){const object=await bucket().get('semantic/raw/'+id);if(!object)throw Error('原始文件不可用');return new Response(object.body,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(d.name),'Cache-Control':'no-store'}})}if(d.status==='active')throw Error('已启用数据不可覆盖');const n=Number(req.headers.get('content-length'));if(!n||n>100*1024*1024)throw Error('文件须在 100 MB 以内');await bucket().put('semantic/raw/'+id,req.body);await db().prepare('UPDATE datasets SET raw=1 WHERE id=?').bind(id).run();return {ok:true}}
 if(path==='semantic/chunk')return semanticIngest(id,body);if(path==='semantic/finish')return finishSemantic(id,body);if(path==='semantic/activate'){const d=await getDataset(id);if(d.status==='active')return {ok:true};if(d.status!=='review'||d.report?.errors)throw Error('请先通过全量质量检查');await db().prepare("UPDATE datasets SET status='active' WHERE id=? AND status='review'").bind(id).run();return {ok:true}}if(path==='semantic/cancel'){const d=await getDataset(id);if(d.status==='active')throw Error('已启用数据不能作为草稿取消');await db().prepare("UPDATE datasets SET status='cancelled' WHERE id=?").bind(id).run();return {ok:true}}throw Error('未知字段映射操作');}
