'use client';
import {useEffect,useState} from 'react';
import {cachedRead,clearReadCache} from '../lib/client-cache';
const number=(v:any,digits=2)=>v==null?'—':Number(v).toLocaleString('zh-CN',{maximumFractionDigits:digits});
const value=(v:any,unit:string)=>v==null?'—':unit==='rate'?number(v*100)+'%':unit==='money'?'$'+number(v):number(v,0);
const change=(m:any)=>m.pp!=null?(m.pp>0?'+':'')+number(m.pp)+' 个百分点':m.relative!=null?(m.relative>0?'+':'')+number(m.relative)+'%':m.previous===0&&m.current>0?'上期为零':m.delta===0?'0%':'无法比较';
export default function Discovery({filters,months,compact=false,onOpen,onShowAll}:any){
 const [mode,setMode]=useState('month'),[month,setMonth]=useState(''),[refresh,setRefresh]=useState(0),[data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[all,setAll]=useState(false);
 const options=(months||[]).filter((m:string)=>!filters.months?.length||filters.months.includes(m));const selected=options.includes(month)?month:options.at(-1)||'';
 const key=JSON.stringify({filters,mode,month:selected});
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setData(null);setAll(false);cachedRead('discover?input='+encodeURIComponent(key),undefined,controller.signal).then(d=>{if(!controller.signal.aborted)setData(d)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[key,refresh]);
 return <section className="card discovery" aria-busy={loading}><div className="cardhead"><div><span className="eyebrow">AUTOMATIC DISCOVERY</span><h2>{compact?'值得关注的变化':'自动发现'}</h2></div><button disabled={loading} onClick={()=>{clearReadCache();setRefresh(v=>v+1)}}>重新扫描</button></div>
 <div className="discovery-controls"><label>观察月份<select value={selected} onChange={e=>setMonth(e.target.value)}>{options.map((m:string)=><option key={m}>{m}</option>)}</select></label><label>对比方式<select value={mode} onChange={e=>setMode(e.target.value)}><option value="month">整月与上一自然月</option><option value="week">最近 7 天与前 7 天</option></select></label><p className="muted">多月或全部月份时，默认扫描最新月。渠道和设备跟随侧栏筛选，商品搜索不影响本区域。</p></div>
 {loading&&<p role="status">正在计算指标并扫描变化…</p>}{error&&<p role="alert">{error}</p>}
 {data?.status==='unavailable'&&<p className="discovery-empty">{data.reason}</p>}
 {data?.status==='ready'&&<>
 <p className="discovery-period"><strong>{data.period.current.start} 至 {data.period.current.end}</strong> 对比 <strong>{data.period.previous.start} 至 {data.period.previous.end}</strong><br/>{data.filters.channel} · {data.filters.device}</p>
 {data.period.current.days!==data.period.previous.days&&<p className="discovery-caution">两期天数不同（{data.period.current.days} / {data.period.previous.days} 天），总量变化包含天数影响。日均GMV {value(data.aggregates.current.revenue/data.period.current.days,'money')} / {value(data.aggregates.previous.revenue/data.period.previous.days,'money')}；日均交易 {number(data.aggregates.current.transactions/data.period.current.days)} / {number(data.aggregates.previous.transactions/data.period.previous.days)}。</p>}
 <p><strong>{data.cards.length?'发现 '+data.cards.length+' 个值得关注的变化':'暂未发现达到规则阈值的变化'}</strong><span className="muted"> · 已检查 {data.metrics.length} 项核心指标；样本不足的项目见下方明细</span></p>
 <div className="discovery-cards">{(all&&!compact?data.cards:data.cards.slice(0,compact?3:8)).map((c:any)=><article key={c.id} className="discovery-item" onClick={()=>onOpen?.(data,c)}><span className="badge">{c.type}</span><h3>{c.title}</h3>{c.unit&&<><strong className="discovery-change">{change(c)}</strong><p>{value(c.previous,c.unit)} → {value(c.current,c.unit)}{c.type==='日度波动'?'（前 7 日均值 → 当天）':''}</p></>}{c.evidence?.map((m:any)=><p key={m.key}>{m.label} <strong>{change(m)}</strong> · {value(m.previous,m.unit)} → {value(m.current,m.unit)}</p>)}<button className="discovery-open">查看分析</button></article>)}</div>
 {compact&&<button onClick={onShowAll}>查看全部发现</button>}
 {!compact&&<>
 {data.cards.length>8&&<button onClick={()=>setAll(v=>!v)}>{all?'收起':'查看全部 '+data.cards.length+' 项'}</button>}
 <button onClick={()=>{const metric=data.metrics.find((m:any)=>m.key==='revenue');onOpen?.(data,{...metric,metric:'revenue',title:'GMV 变化分析'})}}>查看 GMV 拆解</button>
 <details><summary>全部指标、变化与统计口径</summary><div className="tablewrap"><table><thead><tr><th>指标</th><th>上期</th><th>本期</th><th>变化</th><th>扫描结果</th></tr></thead><tbody>{data.metrics.map((m:any)=><tr key={m.key}><td>{m.label}</td><td>{value(m.previous,m.unit)}</td><td>{value(m.current,m.unit)}</td><td>{change(m)}</td><td>{m.reason|| (m.flagged?'达到阈值':'未达到阈值')}</td></tr>)}</tbody></table></div>{data.metrics.map((m:any)=><p key={m.key}><strong>{m.label}</strong> · {m.formula}<br/>依赖字段 {m.dependency}；{m.dedup}；时间范围见上方对比周期，日期采用原始 GA date。</p>)}</details>
 <details><summary>查看指标关系</summary><div className="metric-relations"><p><strong>GMV {value(data.tree.current.revenue,'money')}</strong><br/>= 交易数 {number(data.tree.current.transactions,0)} × 客单价 {value(data.tree.current.aov,'money')}</p><p><strong>交易数 {number(data.tree.current.transactions,0)}</strong><br/>= 购买人数 {number(data.tree.current.buyers,0)} × 每购买用户交易数 {number(data.tree.current.frequency)}</p><p><strong>购买人数 {number(data.tree.current.buyers,0)}</strong><br/>= 访客数 {number(data.tree.current.visitors,0)} × 购买转化率 {value(data.tree.current.conversion,'rate')}</p></div><p className="muted">展示值经过四舍五入。{data.tree.current.note} 点击“查看 GMV 拆解”继续分析贡献。</p></details>
 <details><summary>扫描规则与计算依据</summary><p>数量及金额指标相对变化至少 15%。比例指标绝对变化至少 0.3 个百分点，且相对变化至少 10%；上期为零时不计算相对变化。购买转化率要求两期访客各至少 200，且至少一期有 20 位购买用户。行为比例要求两期分母各至少 100。客单价要求两期各至少 20 笔交易；GMV、交易数要求至少一期 20 笔交易。</p><p>GMV占比变化至少 5 个百分点，且两期总GMV各至少 1,000 USD、分组至少一期 20 笔交易。日度GMV偏离前 7 日均值至少 50%、金额差至少 100 USD，且当天或参考期日均交易至少 10 笔。均为探索性规则，不是统计显著性判断；小样本不自动下结论。</p>{data.notes.map((n:string)=><p key={n}>{n}</p>)}{data.evidence.map((e:any)=><details key={e.name}><summary>{e.name} · SQL</summary><pre>{e.sql}</pre><pre>{JSON.stringify(e.params)}</pre></details>)}<p>扫描时间 {new Date(data.scannedAt).toLocaleString('zh-CN')}</p><pre>{JSON.stringify({sources:data.sourceVersions,aggregates:data.aggregates},null,2)}</pre></details>
 </>} </>}
 </section>
}
