'use client';
import {useCallback,useState} from 'react';
import StepConclusion from './step-conclusion';
import {startSession,visitMetric,recordDimensions,expandDimension,recordDiagnostic,recordBack} from '../lib/analysis-session';
import BehaviorDiagnosis from './behavior-diagnosis';
import DimensionAnalysis from './dimension-analysis';
import GmvContribution from './gmv-contribution';
import {cachedRead} from '../lib/client-cache';
import {pct} from '../lib/discovery/explanation';
const labels:Record<string,string>={revenue:'GMV',transactions:'交易数',aov:'客单价',visitors:'访客数',buyers:'购买访客数',conversion:'购买转化率',frequency:'购买用户人均交易次数'};
const money=(n:number)=>'$'+Number(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const signed=(n:number,u='number')=>(n>0?'+':n<0?'−':'')+(u==='money'?money(Math.abs(n)):Math.abs(n).toLocaleString('zh-CN',{maximumFractionDigits:2}));
const val=(n:any,key:string)=>n==null?'—':['revenue','aov'].includes(key)?money(n):key==='conversion'?(n*100).toFixed(2)+'%':Number(n).toLocaleString('zh-CN',{maximumFractionDigits:key==='frequency'?3:0});
const limitation='当前数据只能定位到此层，需要价格、成本、营销活动等业务数据进一步验证。';
function MetricNode({item,impact,onNext}:any){return <article className="rate-node"><span>{labels[item.key]}</span><strong>{pct(item.relative)}</strong><small>本期 {val(item.current,item.key)} · 上期 {val(item.previous,item.key)}</small>{impact&&<b>{impact}</b>}{onNext&&<button onClick={onNext}>{item.title}</button>}</article>}
function ProductSources({snapshot,onResult}:any){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const load=async()=>{setLoading(true);setError('');try{const result=await cachedRead('discover?input='+encodeURIComponent(JSON.stringify({filters:snapshot.inputFilters,mode:snapshot.period.mode,month:snapshot.period.month,expectedSourceVersions:snapshot.sourceVersions,detail:'product'})));if(result.status!=='ready')throw Error(result.reason);if(JSON.stringify(result.sourceVersions)!==JSON.stringify(snapshot.sourceVersions))throw Error('数据已更新，请重新进入分析');setData(result.detail);onResult?.(result.detail)}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 return <section className="analysis-node"><h3>补充诊断：检查商品结构</h3><p>商品收入与全店 GMV 使用不同原始字段和去重口径，以下是结构线索，不当作全店客单价变化的已证明原因。</p>{!data&&<button disabled={loading} onClick={load}>{loading?'正在计算…':'查看商品结构对比'}</button>}{error&&<p role="alert">{error}</p>}{data&&<><p>商品收入变化最大的商品：{data.groups.slice(0,3).map((r:any)=>r.name+' '+signed(r.revenueDelta,'money')).join('；')}。</p><details><summary>展开完整商品结构对比</summary><div className="tablewrap"><table><thead><tr><th>商品</th><th>上期收入</th><th>本期收入</th><th>上期销量</th><th>本期销量</th><th>本期每件已记录收入</th></tr></thead><tbody>{data.groups.map((r:any)=><tr key={r.id}><td>{r.name}</td><td>{money(r.previous.revenue||0)}</td><td>{money(r.current.revenue||0)}</td><td>{r.previous.quantity||0}</td><td>{r.current.quantity||0}</td><td>{r.currentUnitRevenue==null?'—':money(r.currentUnitRevenue)}</td></tr>)}</tbody></table></div></details></>}<p className="muted">{limitation}</p></section>
}
export default function ReasonAnalysis({snapshot,card,backLabel,onBack,onExplore,onAI}:any){
 const decomposition=snapshot.decomposition,c=decomposition.values.current,p=decomposition.values.previous,key=card.metric||'revenue',gmv=key==='revenue'||card.id==='divergence-revenue';const root=gmv?'revenue':key;const rootMetric=decomposition.metrics[root];
 const [session,setSession]=useState(()=>startSession(snapshot,root,crypto.randomUUID()));
 const [dimensionStart,setDimensionStart]=useState<any>({scope:[],dimension:null,nonce:0,explore:false});
 const record=useCallback((event:any)=>setSession(prev=>event.type==='dimensions'?recordDimensions(prev,event.metric,event.scope,event.data,event.selected,event.explored):event.type==='groups'?expandDimension(prev,event.metric,event.scope,event.dimension):event.type==='back'?recordBack(prev,event.metric,event.scope):recordDiagnostic(prev,event.kind,event.metric,event.scope,event.result,event.explored)),[]);
 const [node,setNode]=useState(root==='transactions'?'transactions':root==='aov'?'aov':root==='visitors'?'visitors':root==='conversion'?'conversion':root==='buyers'?'buyers':''),[source,setSource]=useState('');
 const pathTo=(from:string,target:string):string[]=>{if(from===target)return [from];for(const child of decomposition.config[from]?.children||[]){const path=pathTo(child,target);if(path.length)return [from,...path]}return []};const metricPath=(pathTo(root,node).length?pathTo(root,node):[node]).map(k=>labels[k]);
 const [transactionOpen,setTransactionOpen]=useState(root==='transactions');const navigate=(next:string,action='click')=>{setTransactionOpen(next==='transactions'||pathTo(root,next).includes('transactions'));setNode(next);setSource('');setDimensionStart((v:any)=>({scope:[],dimension:null,nonce:v.nonce+1,explore:false}));setSession(prev=>visitMetric(prev,next,action));if(next==='conversion')setSession(prev=>recordDiagnostic(prev,'behavior',next,[],snapshot.diagnosis,true))};

 const factorItems=decomposition.branches.revenue,lead=factorItems.find((i:any)=>i.key===decomposition.leading.revenue);const tf=decomposition.branches.transactions;const factorLabel=(i:any)=>i.role;const m=snapshot.metrics.find((x:any)=>x.key===root),delta=rootMetric.delta;const [legacy,setLegacy]=useState<any>(null);
 return <section className="card reason-page"><button className="textbtn" onClick={onBack}>{backLabel||'返回经营概览'}</button><h2>{rootMetric.title}</h2><p className="muted">{snapshot.period.current.start} 至 {snapshot.period.current.end} 对比 {snapshot.period.previous.start} 至 {snapshot.period.previous.end} · {snapshot.filters.channel} · {snapshot.filters.device}</p>
 <div className="analysis-totals"><article><span>本期 {labels[root]}</span><strong>{val(c[root],root)}</strong></article><article><span>上期 {labels[root]}</span><strong>{val(p[root],root)}</strong></article><article><span>环比</span><strong>{pct(rootMetric.relative)}</strong></article><article><span>{delta>=0?'增加':'减少'}</span><strong>{root==='conversion'?signed(delta*100)+' 个百分点':signed(delta,['revenue','aov'].includes(root)?'money':'number')}</strong></article></div>
 {snapshot.period.current.days!==snapshot.period.previous.days&&<p className="muted">本期 {snapshot.period.current.days} 天，上期 {snapshot.period.previous.days} 天；总量变化包含天数差异。</p>}
 {gmv&&<><h3>指标驱动 · 先看：交易数与客单价如何变化</h3><p className="formula">GMV = 交易数 × 客单价</p><div className="rate-tree">{factorItems.map((i:any)=><MetricNode key={i.key} item={i} impact={factorLabel(i)} onNext={()=>navigate(i.key)}/>)}</div><StepConclusion text={decomposition.summaries.revenue}/><details><summary>查看乘法关系与指标口径</summary><p>1 + GMV 增长率 = (1 + 交易数增长率) × (1 + 客单价增长率)，增长率按小数代入，不能简单相加。</p><p>{m?.formula}；{m?.dedup}。全店客单价为 GMV / 交易数。</p></details>
 <details className="impact-explanation"><summary>再看：这些变化带来的 GMV 金额影响</summary>{snapshot.contribution.factors.reason?<p>{snapshot.contribution.factors.reason}</p>:<><div className="contribution-factors">{factorItems.map((i:any)=><article key={i.key}><span>{labels[i.key]}变化带来的 GMV 影响</span><strong>{signed(i.amount,'money')}</strong></article>)}</div><p>{decomposition.impactSummary.text}</p></>}<p className="muted">使用原有对称分摊法：交易数差 × 两期客单价均值，客单价差 × 两期交易数均值。相当于对两种替换顺序取平均，交互项 Δ交易数 × Δ客单价各分一半；不做人为补差，属于算术解释，不代表业务因果。</p></details>
 {lead&&<p className="next-step">下一步：优先查看{labels[lead.key]}的变化。点击上方节点继续，也可检查抵消因素。</p>}</>}
 {(node==='transactions'||transactionOpen)&&<section className="analysis-node"><h3>{decomposition.metrics.transactions.title}</h3><p className="formula">交易数 = 访客数 × 购买转化率 × 购买用户人均交易次数</p><p className="muted">购买转化率 = 去重购买人数 / 去重访客；购买用户人均交易次数 = 交易数 / 购买访客数。分母非零时为精确恒等式，重复交易不会被忽略。</p><div className="rate-tree">{tf.map((i:any)=><MetricNode key={i.key} item={i} impact={i.role} onNext={()=>navigate(i.key)}/>)}</div><StepConclusion text={decomposition.summaries.transactions}/>{!tf.length&&<p>分母为零，无法继续按乘法分解。</p>}<details><summary>查看数量影响与分解口径</summary>{tf.map((i:any)=><p key={i.key}>{labels[i.key]}变化带来的交易数影响：{signed(i.amount)}；对应 GMV 影响 {signed(i.gmvImpact,'money')}</p>)}<p>对三个因素的六种替换顺序取平均（Shapley 分解）：双因素交互项由参与的两个因素平分，三因素交互项由三个因素平分；合计为交易数净变化。只衡量算术影响。</p></details></section>}
 {root==='buyers'&&<section className="analysis-node"><h3>购买人数 = 访客数 × 购买转化率</h3><div className="rate-tree">{decomposition.branches.buyers.map((i:any)=><MetricNode key={i.key} item={i} impact={i.role} onNext={()=>navigate(i.key)}/>)}</div><StepConclusion text={decomposition.summaries.buyers}/></section>}
 {node&&node!==root&&<button className="textbtn" onClick={()=>{const path=pathTo(root,node);const parent=path[path.length-2]||root;setTransactionOpen(parent==='transactions');navigate(parent,'back')}}>返回上一级指标：{labels[pathTo(root,node).slice(-2,-1)[0]||root]}</button>}
 {['visitors','conversion','frequency','aov'].includes(node)&&<DimensionAnalysis key={node+':'+dimensionStart.nonce} snapshot={snapshot} metric={node} metricPath={metricPath} initialScope={dimensionStart.scope} initialDimension={dimensionStart.dimension} initialExplore={dimensionStart.explore} responses={session.responses} onRecord={record}/>}
 {node==='conversion'&&<BehaviorDiagnosis diagnosis={snapshot.diagnosis} title="原始筛选范围的行为诊断"/>}
 {node==='aov'&&<ProductSources snapshot={snapshot} onResult={(result:any)=>record({kind:'product',metric:'aov',scope:[],result,explored:true})}/>}
 {node==='frequency'&&<section className="analysis-node"><h3>购买用户人均交易次数 {pct(decomposition.metrics.frequency.relative)}</h3><p>本期 {val(c.frequency,'frequency')}，上期 {val(p.frequency,'frequency')}；这是周期交易数除以去重购买人数，不是订单件数，也不能直接解释为老客复购率。</p><p>{limitation}</p></section>}
 <details><summary>其他定位工具与计算依据</summary><button onClick={async()=>{const result=await cachedRead('discover?input='+encodeURIComponent(JSON.stringify({filters:snapshot.inputFilters,mode:snapshot.period.mode,month:snapshot.period.month})));if(result.status==='ready'&&JSON.stringify(result.sourceVersions)===JSON.stringify(snapshot.sourceVersions)){setLegacy(result.contribution);setSource('gmv')}}}>查看渠道 GMV 金额变化</button><button onClick={onExplore}>查看已有购物行为分析</button>{onAI&&<button onClick={()=>onAI(`请基于当前筛选分析${labels[root]}变化，区分数据事实与待验证原因。`)}>向 AI 继续提问</button>}{source==='gmv'&&<GmvContribution data={legacy||snapshot.contribution}/>}<details><summary>完整指标与查询依据</summary>{snapshot.metrics.map((x:any)=><p key={x.key}>{x.label}：{val(x.previous,x.key)} → {val(x.current,x.key)}；{pct(x.relative)}；{x.formula}；{x.dedup}；{x.reason}</p>)}{snapshot.evidence.map((e:any)=><details key={e.name}><summary>{e.name}</summary><pre>{e.sql}</pre><pre>{JSON.stringify(e.params)}</pre></details>)}</details></details></section>
}
