'use client';
import SemanticWorkspace from './semantic-workspace';
import ShoppingFlow from './shopping-flow';
import Discovery from './discovery';
import ReasonAnalysis from './reason-analysis';
import PeriodContext from './period-context';
import GaBenchmark,{GaStats} from './ga-benchmark';
import {writeGa} from '../lib/ga-client';
import {cachedRead,clearReadCache} from '../lib/client-cache';
import {readGaResponse} from '../lib/ga-response';
import {useEffect,useState,useCallback,useRef} from 'react';
import {AreaChart,Area,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid} from 'recharts';
import {BarChart3,SlidersHorizontal,Sparkles,Settings,ArrowUpRight,Database,ChevronDown,X,Plus,UploadCloud,CheckCircle2,AlertCircle,Send,RefreshCw,FileText,GripVertical,Trash2} from 'lucide-react';
import {labels} from '../lib/labels';
async function api(path:string,body?:any,method?:string,signal?:AbortSignal){const r=await fetch('/api/'+path,{signal,method:method||(body?'POST':'GET'),headers:body?{'Content-Type':'application/json'}:{},...(body?{body:JSON.stringify(body)}:{})});return readGaResponse(r,path.split('?')[0])}
const number=(n:any)=>Number(n||0).toLocaleString('zh-CN',{maximumFractionDigits:0});
const rate=(n:any)=>n==null?'—':(Number(n)*100).toFixed(2)+'%';
const money=(n:any)=>'$'+Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const format=(k:string,v:any)=>v==null?'—':k.includes('conversion')||k==='add_rate'?rate(v):['revenue','aov','product_revenue'].includes(k)?money(v):number(v);
function KpiChange({change,period,loading}:any){const n=change?.relative;return <div className={'kpi-change '+(n>0?'up':n<0?'down':'flat')} title={period?.previous?.length?'本期 '+period.current.join('、')+'；上期 '+period.previous.join('、')+'。环比为相对变化率。':''}>{loading?'计算中…':n==null?(change?.reason||'暂无上期数据'):<><span>{n>0?'▲':n<0?'▼':'●'} {n>0?'+':''}{Number(n).toFixed(2)}%</span><span>环比</span></>}</div>}
function Table({rows,metrics,sort,onSort,loading=false}:any){
 const [localSort,setLocalSort]=useState<any>(null);const current=onSort?sort:localSort;
 const ordered=onSort||!current?rows:[...rows].sort((a:any,b:any)=>{const av=current.key==='dimension'?(a.product_name||a.dimension):a[current.key],bv=current.key==='dimension'?(b.product_name||b.dimension):b[current.key];if(av==null)return bv==null?0:1;if(bv==null)return -1;const value=current.key==='dimension'?String(av).localeCompare(String(bv),'zh-CN'):Number(av)-Number(bv);return current.direction==='asc'?value:-value});
 const header=(key:string,title:string)=><th key={key} aria-sort={current?.key===key?(current.direction==='asc'?'ascending':'descending'):'none'}><button className="sort-header" disabled={loading} onClick={()=>{const next={key,direction:current?.key===key&&current.direction==='desc'?'asc':'desc'};(onSort||setLocalSort)(next)}} aria-label={title+'，点击按'+(current?.key===key&&current.direction==='desc'?'升序':'降序')+'排列'}>{title}<span className="sort-triangles" aria-hidden="true"><span className={current?.key===key&&current.direction==='asc'?'active':''}>▲</span><span className={current?.key===key&&current.direction==='desc'?'active':''}>▼</span></span></button></th>;
 return <div className="tablewrap" aria-busy={loading}><table><thead><tr>{header('dimension','维度')}{metrics.map((m:string)=>header(m,labels[m]||m))}</tr></thead><tbody>{ordered.length?ordered.map((r:any,i:number)=><tr key={i}><td title={r.dimension}>{r.product_name||r.dimension}</td>{metrics.map((m:string)=><td key={m}>{format(m,r[m])}</td>)}</tr>):<tr><td colSpan={metrics.length+1} className="emptycell">{loading?'正在加载…':'当前范围没有数据'}</td></tr>}</tbody></table></div>
}
function Bars({rows,metric}:any){const max=Math.max(...rows.map((r:any)=>Number(r[metric]||0)),1);return <div className="bars">{rows.slice(0,15).map((r:any,i:number)=><div className="barrow" key={i}><span>{r.product_name||r.dimension}</span><div><i style={{width:Math.max(0,100*Number(r[metric]||0)/max)+'%'}}/></div><b>{format(metric,r[metric])}</b></div>)}</div>}
export default function Dashboard({initialAdmin=false}:{initialAdmin?:boolean}){
 const canManage=false; // Dedicated public demo: identical read-only UI for every account.
 const [meta,setMeta]=useState<any>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[admin,setAdmin]=useState(false),[tab,setTab]=useState('data'),[info,setInfo]=useState(false),[aiOpen,setAiOpen]=useState(false),[months,setMonths]=useState<string[]>(['2017-03']),[channel,setChannel]=useState(''),[device,setDevice]=useState(''),[sample,setSample]=useState(false),[data,setData]=useState<any>(null),[products,setProducts]=useState<any>(null),[search,setSearch]=useState(''),[metric,setMetric]=useState('revenue'),[saved,setSaved]=useState<any[]>([]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[question,setQuestion]=useState(''),[messages,setMessages]=useState<any[]>([]),[asking,setAsking]=useState(false),[manage,setManage]=useState<any>(null),[progress,setProgress]=useState(''),[previews,setPreviews]=useState<any[]>([]),[replace,setReplace]=useState(false),[key,setKey]=useState(''),[visitor,setVisitor]=useState(false),[limit,setLimit]=useState(20),[saveDraft,setSaveDraft]=useState<any>(null),[saveName,setSaveName]=useState(''),[saveDisplay,setSaveDisplay]=useState('table'),[follow,setFollow]=useState(true),[position,setPosition]=useState(0);
 const [dataEpoch,setDataEpoch]=useState(0);
 const [view,setView]=useState('overview'),[reason,setReason]=useState<any>(null),[explore,setExplore]=useState('channel'),[grain,setGrain]=useState('day'),[dailyAverage,setDailyAverage]=useState(false);
 function navigate(next:string){if(!['overview','discover','explore'].includes(next))next='overview';setView(next);setAdmin(next==='manage');setAiOpen(next==='ai');setReason(null);if(typeof window!=='undefined')window.history.replaceState(null,'','#'+next)}
 useEffect(()=>{const sync=()=>{const v=window.location.hash.slice(1);if(['overview','discover','explore'].includes(v)){setView(v);setAdmin(v==='manage');setAiOpen(v==='ai')}};sync();window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[]);
 useEffect(()=>{setReason(null);setView(v=>v==='reason'?'overview':v)},[months,channel,device,sample]);
 const openReason=(snapshot:any,card:any)=>{setReason({snapshot,card,returnView:view,sessionId:crypto.randomUUID()});setView('reason');setAdmin(false);window.scrollTo({top:0,behavior:'smooth'})};

 const analysisRequest=useRef(0);useEffect(()=>{analysisRequest.current++;setAnalysisLoading('')},[months,channel,device,sample,view]);
 const [analysisLoading,setAnalysisLoading]=useState('');
 const openKpiAnalysis=async(k:string)=>{const request=++analysisRequest.current;const scope=JSON.stringify({filters:{months,channel,device,sample},mode:'overview'});setAnalysisLoading(k);setError('');try{const snapshot=data?.analysis||await cachedRead('analysis?input='+encodeURIComponent(scope));if(request!==analysisRequest.current)return;if(snapshot.status!=='ready')throw Error(snapshot.reason||'暂无可比数据');const card=snapshot.metrics.find((m:any)=>m.key===k);openReason(snapshot,{...card,metric:k,title:labels[k]+'变化分析'})}catch(e:any){if(request===analysisRequest.current)setError(e.message)}finally{if(request===analysisRequest.current)setAnalysisLoading('')}};
 const [productSort,setProductSort]=useState({key:'product_revenue',direction:'desc'}),[productLoading,setProductLoading]=useState(false);
 const filters={months,channel,device,sample};const filterKey=JSON.stringify(filters);
 const refresh=useCallback(async()=>{clearReadCache();const m=await api('meta');setMeta(m);setDataEpoch(n=>n+1);return m},[]);
 const loadAdmin=useCallback(async()=>{const a=await api('admin');setManage(a);setVisitor(a.settings.visitorEnabled);setLimit(a.settings.dailyLimit)},[]);
 useEffect(()=>{api('meta').then(setMeta).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(admin&&canManage)loadAdmin().catch(e=>setError(e.message))},[admin,canManage,loadAdmin]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setData(null);cachedRead('dashboard?view=overview&filters='+encodeURIComponent(filterKey),undefined,controller.signal).then(d=>{if(!controller.signal.aborted)setData(d)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[filterKey,dataEpoch]);
 useEffect(()=>{if(!canManage||(!(view==='explore'&&explore==='saved')&&!(admin&&tab==='boards')))return;const controller=new AbortController();setSaved([]);api('saved?filters='+encodeURIComponent(filterKey),undefined,undefined,controller.signal).then(s=>{if(!controller.signal.aborted)setSaved(s)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)});return()=>controller.abort()},[filterKey,dataEpoch,view,explore,admin,tab,canManage]);
 useEffect(()=>{if(view!=='explore'||explore!=='product')return;const controller=new AbortController();setProductLoading(true);setProducts(null);const timer=setTimeout(()=>cachedRead('query',{dimension:'product',metrics:['views','adds','add_rate','quantity','product_revenue'],filters:JSON.parse(filterKey),product:search,sort:productSort.key,direction:productSort.direction},controller.signal).then(d=>{if(!controller.signal.aborted)setProducts(d)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setProductLoading(false)}),150);return()=>{controller.abort();clearTimeout(timer)}},[filterKey,search,dataEpoch,productSort,view,explore]);
 const panelDimension=view==='overview'&&grain==='month'?'month':view==='explore'&&explore==='channel'?'channel':view==='explore'&&explore==='behavior'?'device':null;
 const [panel,setPanel]=useState<any>(null),[panelLoading,setPanelLoading]=useState(false);
 const panelKey=JSON.stringify([filterKey,panelDimension,dataEpoch]);
 useEffect(()=>{setPanel(null);if(!panelDimension){setPanelLoading(false);return}const controller=new AbortController();setPanelLoading(true);
 const metrics=panelDimension==='month'?['revenue','transactions','visitors','conversion','aov']:panelDimension==='channel'?['revenue','visitors','buyers','conversion']:['adds','ordered','cart_conversion'];
 cachedRead('query',{dimension:panelDimension,metrics,filters:JSON.parse(filterKey)},controller.signal).then(result=>{if(!controller.signal.aborted)setPanel({key:panelKey,rows:result.rows})}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setPanelLoading(false)});return()=>controller.abort()
 },[panelKey]);
 const panelRows=panel?.key===panelKey?panel.rows:[];
 async function act(fn:()=>Promise<any>){setError('');setNotice('');setBusy(true);try{await fn()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function ask(q=question){if(!q.trim()||asking)return;setQuestion('');setMessages(m=>[...m,{question:q}]);setAsking(true);try{const result=await api('ask',{question:q,filters,history:messages.slice(-8).map(m=>({role:m.question?'user':'assistant',content:m.question||m.clarification||m.answer||m.error||''}))});setMessages(m=>[...m,{...result}])}catch(e:any){setMessages(m=>[...m,{error:e.message}])}finally{setAsking(false)}}
 function save(result:any,item?:any){setSaveDraft(result);setSaveName(item?.name||'我的分析');setSaveDisplay(item?.display||'table');setFollow(item?!!item.follow:true);setPosition(item?.position||saved.length);}
 async function upload(files:FileList|null){if(!files?.length)return;await act(async()=>{setPreviews([]);for(const file of Array.from(files)){const importStarted=performance.now();if(!/\.jsonl(\(\d+\))?(\.gz)?$/i.test(file.name))throw Error('请上传准备好的 .jsonl 或 .jsonl.gz 文件');if(file.size>100*1024*1024)throw Error('文件超过 100 MB，请使用 gzip 压缩后的文件');setProgress('校验文件 · '+file.name);const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))).map(x=>x.toString(16).padStart(2,'0')).join('');const start=await api('import/start',{name:file.name,hash});if(start.duplicate){if(start.status==='ready'){const r=await api('import/preview?id='+start.id,{});setPreviews(p=>[...p,{id:start.id,name:file.name,...r}])}else setNotice(file.name+' 已导入，已跳过重复文件');continue}const id=start.id;try{setProgress('保留原始文件 · '+file.name);const upload=await fetch('/api/import/raw?id='+id,{method:'POST',body:file});if(!upload.ok)throw Error(((await upload.json()) as any).error);const stats=await writeGa(file,file.name,id,setProgress);const r=await api('import/preview?id='+id,{});stats.totalMs=performance.now()-importStarted;await api('import/performance?id='+id,{stats});r.performance=stats;setPreviews(p=>[...p,{id,name:file.name,...r}])}catch(e){await api('import/cancel?id='+id,{}).catch(()=>{});throw e}}setProgress('检查完成，请核对下方预览后确认导入');await loadAdmin()})}
 const hasData=sample?meta?.sampleReady:meta?.months?.length>0;const monthOptions=sample?['2017-01']:(meta?.months||[]).map((m:any)=>m.month);const title=sample?'验证分析流程':'生意发生了什么？';
 return <div className="app"><header className="topbar"><a className="brand" href="/"><span className="brandmark">数</span><span>经营数据智能诊断平台<small>电商经营分析 · 公开演示</small></span></a><nav aria-label="主导航">{[['overview','经营概览'],['discover','自动发现'],['explore','深度分析'],['ai','AI 分析师'],['manage','数据管理']].filter(([id])=>canManage||!['ai','manage'].includes(id)).map(([id,label])=><button key={id} aria-current={(admin?id==='manage':view===id||view==='reason'&&id==='discover')?'page':undefined} className={(admin?id==='manage':view===id||view==='reason'&&id==='discover')?'active':''} onClick={()=>navigate(id)}>{label}</button>)}</nav></header>
 {error&&<div role="alert" className="toast error"><AlertCircle size={18}/>{error}<button aria-label="关闭错误" onClick={()=>setError('')}><X size={16}/></button></div>}{notice&&<div role="status" className="toast"><CheckCircle2 size={18}/>{notice}<button aria-label="关闭提示" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 <div className={'workspace '+(aiOpen?'with-ai':'')}><aside className="sidebar"><div className="sidebarhead"><span className="eyebrow">FILTERS</span><button onClick={()=>{setMonths([]);setChannel('');setDevice('')}}>重置</button></div><h2>分析范围</h2><label>观察月份</label><details className="monthselect"><summary>{months.length?months.join('、'):'全部月份'}<ChevronDown size={15}/></summary><div>{monthOptions.length>0&&<label><input type="checkbox" checked={!months.length} onChange={()=>setMonths([])}/>全部月份</label>}{monthOptions.length?monthOptions.map((m:string)=><label key={m}><input type="checkbox" checked={months.includes(m)} onChange={e=>setMonths(e.target.checked?[...months,m]:months.filter(x=>x!==m))}/>{m}</label>):<p>导入数据后可选择</p>}</div></details><label htmlFor="channel">渠道</label><select id="channel" value={channel} onChange={e=>setChannel(e.target.value)}><option value="">全部渠道</option>{(sample?['Organic Search','Direct','Referral','Social','Paid Search','Affiliates','Display']:meta?.channels||[]).map((c:string)=><option key={c}>{c}</option>)}</select><label htmlFor="device">设备</label><select id="device" value={device} onChange={e=>setDevice(e.target.value)}><option value="">全部设备</option><option value="desktop">电脑</option><option value="mobile">手机</option><option value="tablet">平板</option></select><div className="samplebox"><Database size={18}/><small>{sample?'开发样例':'正式数据'}</small><strong>{hasData?number(data?.total?.sessions):'等待导入'}</strong><small>{hasData?'当前范围内的会话':'完整月份数据导入后展示'}</small></div>{canManage&&<button className="sampletoggle" disabled={busy} onClick={()=>act(async()=>{if(!meta.sampleReady&&!sample){setProgress('准备样例');await api('sample',{});await refresh()}setSample(!sample);setMonths([]);setChannel('');setDevice('');navigate('overview')})}>{sample?'切换正式数据':'用 90 条样例验证功能'}</button>}<p className="sidehint">月份、渠道和设备联动全店指标。商品筛选只作用于商品分析。</p><div className="sourcefoot">GOOGLE MERCHANDISE STORE<br/>公开数据 · USD</div></aside>
 <main>{admin?(canManage?<><div className="pageheading"><div><span className="eyebrow">WORKSPACE SETTINGS</span><h1>管理你的分析台</h1><p>数据、看板和 AI 用量，都在这里管理。</p></div></div><div className="tabs">{[['semantic','字段映射与质量'],['data','GA 数据'],['boards','看板管理'],['model','模型与额度']].map(([id,name])=><button className={tab===id?'selected':''} key={id} onClick={()=>setTab(id)}>{name}</button>)}</div>
 {tab==='semantic'&&<SemanticWorkspace/>}
 {tab==='data'&&<><section className="card"><div className="cardhead"><div><span className="eyebrow">DATA IMPORT</span><h2>让真实数据进入看板</h2></div><span className="badge">原始文件保留</span></div><div className="steps">{['选择文件','检查与整理','核对预览','确认导入'].map((s,i)=><span key={s}><b>{i+1}</b>{s}</span>)}</div><label className={'dropzone '+(busy?'disabled':'')}><UploadCloud size={32}/><strong>{busy?'正在处理，请保留此页面':'选择一个或多个数据文件'}</strong><span>支持 .jsonl / .jsonl.gz，每个文件不超过 100 MB</span><input disabled={busy} type="file" multiple accept=".gz,.jsonl" onChange={e=>{upload(e.target.files);e.target.value=''}}/></label><p className="muted">上传已准备好的完整月份会话文件。会逐批检查，不会一次解压到服务器内存中。1 月需匹配已核对的 64,694 条会话、53,041 位访客、662 位购买访客、713 笔交易及 300,074 条行为。</p>{progress&&<div className="progress" role="status">{busy&&<RefreshCw size={16} className="spin"/>}{progress}</div>}
 {previews.map(p=><div className="importpreview" key={p.id}><h3>{p.name}</h3><GaStats stats={p.performance}/><div className="tablewrap"><table><thead><tr>{['月份','会话','访客','购买人数','交易','覆盖天数','更新方式'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{p.months.map((m:any)=><tr key={m.month}><td>{m.month}</td><td>{number(m.sessions)}</td><td>{number(m.visitors)}</td><td>{number(m.buyers)}</td><td>{number(m.transactions)}</td><td>{m.days}{!m.fullMonth?' · 不完整':''}</td><td>{m.replaces?'替换已有月份':'新增月份'}</td></tr>)}</tbody></table></div><details><summary>查看检查结果与清洗规则</summary>{p.rules.map((r:string)=><p key={r}>{r}</p>)}{p.months.map((m:any)=><p key={m.month}>{m.month} · 购买事件 {m.purchase_events} 次，按会话去重交易标识 {m.transaction_ids} 个，缺失交易标识 {m.missing_ids} 次。</p>)}</details>{p.months.some((m:any)=>m.replaces)&&<label className="check"><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/>我确认用此文件替换已有月份的全部数据</label>}<button className="primary" disabled={busy||p.months.some((m:any)=>!m.fullMonth)} onClick={()=>act(async()=>{await api('import/commit?id='+p.id,{replace});setPreviews(x=>x.filter(v=>v.id!==p.id));setSample(false);await refresh();await loadAdmin();setNotice('导入成功，正式看板已更新')})}>确认导入</button><button disabled={busy} onClick={()=>act(async()=>{await api('import/cancel?id='+p.id,{});setPreviews(x=>x.filter(v=>v.id!==p.id));await loadAdmin()})}>取消本次导入</button></div>)}</section>
 <section className="card"><h2>导入记录</h2><div className="tablewrap"><table><thead><tr><th>文件</th><th>状态</th><th>时间</th><th>操作</th></tr></thead><tbody>{manage?.imports?.map((i:any)=><tr key={i.id}><td>{i.name}</td><td>{{loading:'处理中',ready:'待确认',committed:'已导入',failed:'检查失败',cancelled:'已取消',sample:'开发样例',benchmark_done:'对照通过',benchmark_mismatch:'对照不一致'}[i.status as string]||i.status}</td><td>{new Date(i.created).toLocaleString('zh-CN')}</td><td>{i.sample===2&&['loading','failed','cancelled'].includes(i.status)&&<button disabled={busy} onClick={()=>act(async()=>{await api('import/benchmark-cleanup?id='+i.id,{});await loadAdmin();setNotice('测试数据已清理，正式数据不受影响')})}>清理中断测试</button>}{i.report&&<GaStats stats={JSON.parse(i.report).performance}/>} {i.status==='committed'&&i.raw===1&&<GaBenchmark source={i} disabled={busy} onRunning={setBusy}/>} {i.raw===1&&<a href={'/api/import/raw?id='+i.id}>下载原始文件</a>}{i.status==='ready'&&<button onClick={()=>act(async()=>{const p=await api('import/preview?id='+i.id,{});setPreviews(x=>[...x.filter(v=>v.id!==i.id),{id:i.id,name:i.name,...p}])})}>查看预览</button>}</td></tr>)}</tbody></table></div>{!manage?.imports?.length&&<p className="muted">还没有导入记录。</p>}</section></>}
 {tab==='boards'&&<section className="card"><h2>已保存的分析</h2><p className="muted">在 AI 回答或商品分析中点击“添加到看板”。顺序数字越小越靠前。</p>{saved.length?saved.map(s=><div className="manageitem" key={s.id}><GripVertical size={18}/><div><strong>{s.name}</strong><small>{s.follow?'跟随当前筛选':'固定保存时的筛选'} · 顺序 {s.position}</small></div><button onClick={()=>save({...s.result,id:s.id},s)}>编辑</button><button aria-label={'删除'+s.name} onClick={()=>act(async()=>{await api('saved',{id:s.id},'DELETE');await refresh()})}><Trash2 size={16}/></button></div>):<div className="emptymini">还没有保存分析，去看板探索一下。</div>}</section>}
 {tab==='model'&&<><section className="card"><h2>DeepSeek 模型</h2><p className="muted">密钥仅通过加密连接提交，服务端加密保存，不会返回访客浏览器。</p><span className={'badge '+(manage?.settings?.configured?'good':'')}>{manage?.settings?.configured?'已配置':'未配置'}</span><label htmlFor="key">API 密钥</label><input id="key" autoComplete="new-password" type="password" value={key} placeholder="输入新密钥，留空则保留现有配置" onChange={e=>setKey(e.target.value)}/><div className="actions"><button className="primary" disabled={busy||!key} onClick={()=>act(async()=>{await api('settings',{key});setKey('');await loadAdmin();await refresh();setNotice('密钥已安全保存')})}>保存密钥</button><button disabled={busy||!manage?.settings?.configured} onClick={()=>act(async()=>{const r=await api('model-test',{});setNotice('连接成功，本次使用 '+r.tokens+' tokens')})}>测试连接</button><button disabled={busy} onClick={()=>act(async()=>{await api('settings',{removeKey:true,visitorEnabled:false});await loadAdmin();await refresh();setNotice('密钥已移除，访客 AI 已关闭')})}>移除密钥</button></div><p className="muted">模型 deepseek-flash · 只执行受约束的聚合查询，不执行模型生成的任意 SQL。</p></section><section className="card"><h2>访客使用额度</h2><label className="switchrow"><span><strong>开放访客 AI</strong><small>关闭后，尚有剩余额度的访客也无法提问</small></span><input type="checkbox" checked={visitor} onChange={e=>setVisitor(e.target.checked)}/></label><label htmlFor="limit">每日访客总成功调用上限（UTC 日期）</label><input id="limit" type="number" min="0" max="1000" value={limit} onChange={e=>setLimit(Number(e.target.value))}/><p className="muted">每个匿名浏览器累计 3 次成功提问，失败与澄清不扣次数。并发请求预留额度，另有每分钟服务端限流。匿名浏览器不等于现实中的同一个人。</p><button className="primary" disabled={busy} onClick={()=>act(async()=>{await api('settings',{visitorEnabled:visitor,dailyLimit:limit});await loadAdmin();await refresh();setNotice('访客设置已更新')})}>保存设置</button></section><section className="card"><h2>调用与消耗记录</h2><p className="muted">显示模型返回的 token 用量；金额请以 DeepSeek 账单为准。连接测试不计入提问记录。</p><div className="tablewrap"><table><thead><tr><th>问题</th><th>状态</th><th>Tokens</th><th>时间</th></tr></thead><tbody>{manage?.calls?.map((c:any)=><tr key={c.id}><td>{c.question}</td><td>{{success:'成功',failed:'失败',pending:'处理中',clarification:'待澄清'}[c.status as string]}</td><td>{number(c.tokens)}</td><td>{new Date(c.created).toLocaleString('zh-CN')}</td></tr>)}</tbody></table></div></section></>}
 </>:<section className="card"><h1>数据管理</h1><p>登录所有者账号后可管理数据与模型设置。</p><a href="/signin-with-chatgpt?return_to=%2Fadmin" target="_top">管理登录</a></section>):<><div className="pageheading" hidden={view==='reason'}><div><span className="eyebrow">PERFORMANCE OVERVIEW</span><h1>{view==='overview'?'经营概览':view==='discover'?'自动发现':view==='explore'?'深度分析':view==='reason'?'变化分析':'AI 分析师'}</h1><p>{sample?'90 条刻意分层抽取的会话，仅验证功能，不代表真实经营表现':hasData?(view==='overview'?'查看核心指标，沿着环比变化继续分析':view==='discover'?'选择一项变化，查看指标和来源':view==='explore'?'按问题选择分析维度':view==='reason'?'沿着指标、贡献和子维度逐层查看':'带着具体问题，结合数据继续分析'):'基于真实公开电商数据，让每一个结论都有据可查'}</p></div><span className="badge">{sample?'开发验证':meta?.months?.length?'数据截至 '+meta.months.at(-1).cutoff:'等待完整数据'}</span></div>{sample&&<div className="samplealert"><AlertCircle size={18}/>样例包含三类各 30 条会话，所有比例均有抽样偏差，不用于正式结论。</div>}
 {view==='overview'&&<><div className="demo-context"><strong>公开演示 · 个人数据分析项目</strong><p>基于 Google Analytics 公开电商样例。默认案例为 2017 年 3 月对比 2 月；点击指标的“查看分析”，体验指标拆解与渠道、设备下钻。</p></div><section className="kpis" aria-busy={loading}>{['revenue','transactions','aov','visitors','buyers','conversion'].map((k,i)=><article className="kpi" key={k}><div><span>{labels[k]}</span><span className="kpiicon">{['$','单','$','人','人','%'][i]}</span></div><strong>{hasData?format(k,data?.total?.[k]):'—'}</strong><KpiChange change={data?.comparison?.changes?.[k]} period={data?.comparison} loading={loading}/><small>{k==='conversion'?'购买人数 ÷ 访客数':k==='aov'?'GMV ÷ 交易数':k==='revenue'?'USD · 已记录金额':k==='visitors'||k==='buyers'?'筛选范围内去重':'会话交易数汇总'}</small>{!loading&&data?.comparison?.changes?.[k]?.relative!=null&&<button className="kpi-analysis" disabled={!!analysisLoading} onClick={()=>openKpiAnalysis(k)} aria-label={'查看'+labels[k]+'分析'}>{analysisLoading===k?'加载中…':'查看分析'}</button>}</article>)}</section><PeriodContext data={data} sample={sample}/></>}
 {!hasData?<section className="card emptyhero"><div className="emptyicon"><Database size={30}/></div><h2>看板已准备好，等待真实数据</h2><p>完整 1 月数据导入后，趋势、渠道、商品和购物行为会自动计算。</p>{canManage&&<div className="actions"><button className="primary" onClick={()=>{setAdmin(true);setTab('data')}}>导入完整 1 月数据</button><button disabled={busy} onClick={()=>act(async()=>{if(!meta.sampleReady)await api('sample',{});await refresh();setSample(true);setMonths([])})}>{busy?'正在准备样例…':'先用样例验证功能'}</button></div>}<small>不会用开发样例冒充全店指标</small></section>:<>
 {view==='overview'&&<><section className="card"><div className="cardhead"><div><span className="eyebrow">TREND</span><h2>经营趋势</h2></div><div className="trend-controls"><select aria-label="时间粒度" value={grain} onChange={e=>setGrain(e.target.value)}><option value="month">按月</option><option value="day">按日</option></select><select aria-label="趋势指标" value={metric} onChange={e=>setMetric(e.target.value)}>{['revenue','visitors','transactions','conversion','aov'].map(m=><option key={m} value={m}>{labels[m]}</option>)}</select>{grain==='month'&&['revenue','transactions'].includes(metric)&&<label><input type="checkbox" checked={dailyAverage} onChange={e=>setDailyAverage(e.target.checked)}/>日均口径</label>}</div></div>{grain==='month'&&panelLoading&&<p role="status">正在加载月度趋势…</p>}<div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={grain==='day'?(data?.trend||[]):panelRows.map((r:any)=>({...r,[metric]:dailyAverage&&['revenue','transactions'].includes(metric)?r[metric]/new Date(Number(r.dimension.slice(0,4)),Number(r.dimension.slice(5)),0).getDate():r[metric]}))} margin={{top:16,right:15,bottom:0,left:6}}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#176b4d" stopOpacity={.18}/><stop offset="100%" stopColor="#176b4d" stopOpacity={.015}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e9eeea"/><XAxis dataKey="dimension" tickFormatter={s=>s.slice(5)} tick={{fontSize:12}} axisLine={false} tickLine={false} minTickGap={25}/><YAxis tickFormatter={v=>metric==='conversion'?rate(v):v>=1000?(v/1000).toFixed(1)+'k':number(v)} domain={[0,'auto']} width={65} tick={{fontSize:12}} axisLine={false} tickLine={false}/><Tooltip formatter={(v:any)=>[format(metric,v),labels[metric]]}/><Area type="linear" dataKey={metric} stroke="#176b4d" fill="url(#fill)" strokeWidth={2.5}/></AreaChart></ResponsiveContainer></div><div className="chartfoot"><span><i/>{labels[metric]} · {grain==='day'?'每日':dailyAverage&&['revenue','transactions'].includes(metric)?'月度日均':'月度总览'}</span><small>悬停查看明细</small></div></section></>}
 {view==='discover'&&<Discovery filters={filters} months={monthOptions} compact={false} onOpen={openReason} onShowAll={()=>navigate('discover')}/>}
 {view==='reason'&&reason&&<ReasonAnalysis key={reason.sessionId} {...reason} backLabel={reason.returnView==='overview'?'返回经营概览':'返回自动发现'} onBack={()=>navigate(reason.returnView||'overview')} onExplore={()=>{navigate('explore');setExplore('behavior')}} onAI={canManage?(q:string)=>{navigate('ai');setQuestion(q)}:undefined}/>}
 {view==='ai'&&canManage&&<section className="card"><h2>从发现继续提问</h2><p>右侧可查询 GMV、渠道、商品和购物行为，也可以从自动发现中选择变化后继续分析。</p><button onClick={()=>navigate('discover')}>选择一项发现</button><button onClick={()=>setAiOpen(true)}>打开对话</button></section>}
 {view==='explore'&&<><div className="tabs explore-tabs">{[['channel','渠道'],['behavior','设备与行为'],['product','商品'],['saved','已保存分析']].filter(([id])=>canManage||id!=='saved').map(([id,label])=><button key={id} className={explore===id?'selected':''} onClick={()=>setExplore(id)}>{label}</button>)}</div>
 {explore==='channel'&&<>{panelLoading&&<p role="status">正在加载渠道数据…</p>}<section className="card"><div className="cardhead"><div><span className="eyebrow">CHANNEL PERFORMANCE</span><h2>GMV来自哪里？</h2></div></div><Bars rows={panelRows} metric="revenue"/><p className="insight">结合流量与购买转化率判断渠道表现。GMV差异本身不能证明渠道投放效果。</p></section>
 <section className="card"><div className="cardhead"><div><span className="eyebrow">ACQUISITION</span><h2>渠道表现</h2></div>{canManage&&<button className="textbtn" onClick={()=>{setAiOpen(true);setQuestion('比较当前范围内各渠道的访客数、购买转化率和GMV')}}><Sparkles size={15}/>让 AI 解读</button>}</div><Table rows={panelRows} metrics={['visitors','buyers','conversion','revenue']}/></section>
 </>}
 {explore==='behavior'&&<>{panelLoading&&<p role="status">正在加载设备数据…</p>}
 <section className="card"><div className="cardhead"><div><span className="eyebrow">SHOPPING BEHAVIOR</span><h2>购物行为</h2></div><span className="badge">会话口径</span></div><ShoppingFlow funnel={data?.funnel} transitions={data?.transitions}/><div className="behaviorbottom"><div className="callout"><small>同会话、同商品 · 先加购再购买</small><strong>{rate(data?.funnel?.cart_conversion)}</strong><span>{number(data?.funnel?.ordered)} 个成功会话 / {number(data?.funnel?.adds)} 个加购会话</span></div><Table rows={panelRows} metrics={['adds','ordered','cart_conversion']}/></div></section>
 </>}
 {explore==='product'&&<section className="card"><div className="cardhead"><div><span className="eyebrow">PRODUCT EXPLORER</span><h2>商品表现</h2></div>{canManage&&!sample&&<button disabled={productLoading} onClick={()=>save(products)}><Plus size={16}/>添加到看板</button>}</div><div className="producttools"><input aria-label="搜索商品" placeholder="搜索商品名称或编号" value={search} onChange={e=>setSearch(e.target.value)}/><span>{productLoading?'正在排序…':'仅筛选本区域 · 按所选列排序，最多显示 100 件商品'}</span></div><Table rows={products?.rows||[]} metrics={['views','adds','add_rate','quantity','product_revenue']} sort={{key:products?.plan?.sort||'product_revenue',direction:products?.plan?.direction||'desc'}} onSort={setProductSort} loading={productLoading}/><p className="muted">浏览指商品详情浏览，不含列表曝光。加购比例的分母为浏览该商品的会话，分子为其中也发生加购的会话。商品购买按交易编号去重，缺失交易编号不计入销量和GMV。</p></section>}
 {explore==='saved'&&<>{!saved.length&&<section className="card"><p>还没有保存的分析。</p></section>}{saved.length>0&&<div className="savedheading"><span className="eyebrow">SAVED INSIGHTS</span><h2>你的分析看板</h2></div>}{saved.map(s=><section className="card" key={s.id}><div className="cardhead"><h2>{s.name}</h2><span className="badge">{s.follow?'跟随筛选':'固定范围'}</span></div>{s.error?<p>{s.error}</p>:s.display==='bar'?<Bars rows={s.result.rows} metric={s.result.plan.metrics[0]}/>:<Table rows={s.result.rows} metrics={s.result.plan.metrics}/>}</section>)}</>}</>} </>}
 <footer><button className="textbtn" onClick={()=>setInfo(true)}>数据来源与指标口径</button><br/>个人数据分析项目 · 本地合成演示数据 · 不代表 Google 当前经营情况<br/>GMV 按原始记录金额汇总，缺失金额按 0 处理；数据不能单独证明业务变化原因。</footer></>}
 </main>
 {aiOpen&&canManage&&<aside className="aipanel"><div className="aihead"><div><Sparkles size={20}/><strong>AI 分析师</strong></div><button aria-label="关闭 AI 助手" onClick={()=>setAiOpen(false)}><X size={19}/></button></div><div className="aicontext">基于当前月份、渠道与设备筛选{sample?' · 开发样例':''}</div><div className="aichat">{!messages.length&&<><div className="aiwelcome"><div className="sparkbadge"><Sparkles size={26}/></div><h2>从一个好问题开始</h2><p>查询真实数据，展开结果和 SQL，逐步找到值得关注的变化。</p></div>{['当前各渠道的GMV和购买转化率分别是多少？','哪些商品浏览多，但浏览会话加购比例低？','手机端加购后购买比例，比电脑端低多少？'].map(q=><button key={q} className="example" onClick={()=>setQuestion(q)}>{q}<ArrowUpRight size={15}/></button>)}{!meta?.configured&&<p className="ainote">模型尚未配置。所有者可在管理后台连接 DeepSeek。</p>}{!canManage&&!meta?.visitorEnabled&&<p className="ainote">访客 AI 暂未开放，仍可浏览经营看板。</p>}</>}{messages.map((m,i)=><div key={i} className={m.question?'question':'answer'}>{m.question||m.error||m.clarification||m.answer}{m.error&&<small>本次未扣除成功提问额度</small>}{m.rows&&<><Table rows={m.rows} metrics={m.plan.metrics}/><p className="scope">{m.scope}</p><details><summary>查看 SQL 与统计范围</summary><pre>{m.sql}</pre><pre>{JSON.stringify(m.params,null,2)}</pre><p>{JSON.stringify(m.plan.filters)}</p></details>{canManage&&!sample&&<button onClick={()=>save(m)}><Plus size={15}/>添加到看板</button>}{m.remaining!=null&&<small>剩余 {m.remaining} 次成功提问</small>}</>}</div>)}{asking&&<div className="thinking"><RefreshCw className="spin" size={16}/>正在查询并分析数据…</div>}</div><form className="askform" onSubmit={e=>{e.preventDefault();ask()}}><textarea aria-label="分析问题" placeholder="询问GMV、渠道、商品或购物行为…" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={1000}/><div><small>结论以实际数据为依据</small><button className="primary" aria-label="发送问题" disabled={asking||!question.trim()||!meta?.configured||(!canManage&&!meta?.visitorEnabled)}><Send size={17}/></button></div></form></aside>}
 </div>
 {info&&<div className="overlay" onClick={()=>setInfo(false)}><section className="modal" onClick={e=>e.stopPropagation()}><div className="cardhead"><h2>数据来源与指标口径</h2><button aria-label="关闭" onClick={()=>setInfo(false)}><X size={20}/></button></div><p>本地仓库默认使用人工生成的合成会话数据，覆盖 2017 年 2—3 月，仅用于功能演示；真实历史案例见 README。</p><dl><dt>访客数与购买人数</dt><dd>使用 fullVisitorId 在所选月份范围内去重。购买人数只统计 totals.transactions 大于 0 的访客。</dd><dt>交易数与GMV</dt><dd>交易数汇总 totals.transactions；GMV汇总 totals.transactionRevenue，并除以 1,000,000 转为美元。空值按 0 处理，不代表实际GMV必为零。</dd><dt>客单价与购买转化率</dt><dd>分别为GMV / 交易数、购买人数 / 访客数。分母为 0 时不显示比例。</dd><dt>商品与行为</dt><dd>商品详情浏览对应 action_type=2，加购为 3，结账为 5，购买为 6。购买商品按会话、交易编号、商品编号合并，取重复记录中的最大已记录数量和GMV，再汇总。它与全店GMV可能不一致。</dd><dt>加购后购买</dt><dd>同一会话内，同一商品的购买发生在加购之后。全店分母为所有加购会话，分子为至少一件商品满足该顺序的会话。此口径不包含跨会话购买。</dd><dt>项目用途</dt><dd>用于数据分析作品展示与探索。分层样例只验证功能，不用于店铺结论。现有字段不能证明促销、价格等因素造成了变化。</dd></dl></section></div>}
 {saveDraft&&<div className="overlay"><section className="modal small"><div className="cardhead"><h2>{saveDraft.id?'编辑分析':'添加到看板'}</h2><button aria-label="关闭" onClick={()=>setSaveDraft(null)}><X size={19}/></button></div><label>名称<input value={saveName} onChange={e=>setSaveName(e.target.value)} maxLength={80}/></label><label>展示形式<select value={saveDisplay} onChange={e=>setSaveDisplay(e.target.value)}><option value="table">结果表</option><option value="bar">条形图（首个指标）</option></select></label><label>排列顺序<input type="number" value={position} onChange={e=>setPosition(Number(e.target.value))}/></label><label className="check"><input type="checkbox" checked={follow} onChange={e=>setFollow(e.target.checked)}/>跟随当前月份、渠道与设备筛选</label><button className="primary" disabled={busy||!saveName.trim()} onClick={()=>act(async()=>{await api('saved',{id:saveDraft.id,name:saveName,plan:saveDraft.plan,display:saveDisplay,follow,position});setSaveDraft(null);await refresh();setNotice('分析已保存到看板')})}>保存分析</button></section></div>}
 </div>
}
