import {sqliteTable,text,integer,real,index,primaryKey} from 'drizzle-orm/sqlite-core';
export const imports=sqliteTable('imports',{id:text().primaryKey(),hash:text().notNull(),name:text().notNull(),status:text().notNull(),sample:integer().notNull().default(0),created:text().notNull(),report:text(),raw:integer().notNull().default(0)});
export const months=sqliteTable('months',{month:text().primaryKey(),importId:text('import_id').notNull()});
export const chunks=sqliteTable('chunks',{importId:text('import_id').notNull(),n:integer().notNull()},t=>[primaryKey({columns:[t.importId,t.n]})]);
export const sessions=sqliteTable('sessions',{importId:text('import_id').notNull(),sid:text().notNull(),date:text().notNull(),month:text().notNull(),visitor:text().notNull(),channel:text().notNull(),device:text().notNull(),transactions:integer().notNull(),revenue:real().notNull(),buyer:integer().notNull(),views:integer().notNull(),adds:integer().notNull(),checkouts:integer().notNull(),purchases:integer().notNull(),ordered:integer().notNull(),hits:integer().notNull(),purchaseEvents:integer('purchase_events').notNull(),transactionIds:integer('transaction_ids').notNull(),missingIds:integer('missing_ids').notNull()},t=>[primaryKey({columns:[t.importId,t.sid]}),index('sessions_month_import').on(t.month,t.importId)]);
export const products=sqliteTable('products',{importId:text('import_id').notNull(),sid:text().notNull(),sku:text().notNull(),name:text().notNull(),category:text().notNull(),views:integer().notNull(),adds:integer().notNull(),checkouts:integer().notNull(),purchases:integer().notNull(),ordered:integer().notNull(),quantity:real().notNull(),revenue:real().notNull()},t=>[primaryKey({columns:[t.importId,t.sid,t.sku]})]);
export const settings=sqliteTable('settings',{key:text().primaryKey(),value:text().notNull()});
export const saved=sqliteTable('saved',{id:text().primaryKey(),name:text().notNull(),plan:text().notNull(),follow:integer().notNull().default(1),display:text().notNull().default('table'),position:integer().notNull().default(0)});
export const calls=sqliteTable('calls',{id:text().primaryKey(),visitor:text().notNull(),ip:text().notNull(),day:text().notNull(),status:text().notNull(),created:text().notNull(),question:text().notNull(),tokens:integer().notNull().default(0),plan:text(),sql:text(),result:text()},t=>[index('calls_visitor_status').on(t.visitor,t.status),index('calls_day_status').on(t.day,t.status)]);
// P0 semantic imports are isolated from the existing GA data adapter.
export const datasets=sqliteTable('datasets',{id:text().primaryKey(),name:text().notNull(),hash:text().notNull(),status:text().notNull(),created:text().notNull(),headers:text().notNull(),profile:text().notNull(),config:text(),report:text(),raw:integer().notNull().default(0),revision:integer().notNull().default(1)});
export const standardRows=sqliteTable('standard_rows',{datasetId:text('dataset_id').notNull(),rowNo:integer('row_no').notNull(),rowHash:text('row_hash').notNull(),orderId:text('order_id'),userId:text('user_id'),amount:real(),quantity:real(),eventTime:text('event_time'),eventDate:text('event_date'),channel:text(),device:text(),productId:text('product_id'),productName:text('product_name'),category:text(),eventType:text('event_type'),eventId:text('event_id'),sessionId:text('session_id'),lineId:text('line_id'),region:text(),userType:text('user_type'),issues:text().notNull()},t=>[primaryKey({columns:[t.datasetId,t.rowNo]}),index('standard_rows_order').on(t.datasetId,t.orderId),index('standard_rows_hash').on(t.datasetId,t.rowHash),index('standard_rows_event').on(t.datasetId,t.eventId)]);
export const semanticChunks=sqliteTable('semantic_chunks',{datasetId:text('dataset_id').notNull(),n:integer().notNull(),digest:text().notNull(),count:integer().notNull()},t=>[primaryKey({columns:[t.datasetId,t.n]})]);
